! Auto-generated by generate_code.py

module cht_02

implicit none

! Global constants
real(8), parameter :: rA = 1.0
real(8), parameter :: rAB = 0.75
real(8), parameter :: rB = 0.5
real(8), parameter :: alphaA = 2.0
real(8), parameter :: alphaB = 1.0
real(8), parameter :: wA = 1.0
real(8), parameter :: wB = -1.0
real(8), parameter :: n = 4

contains

! Subroutine uA
subroutine uA(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = r*wA*(-beta1*beta2*rAB*(r - rA)*sin(beta2*theta)*cos(theta) - (beta1*rAB *cos(beta2 &
        *theta) - rA + rAB)*sin(theta))/(beta1*rAB*cos(beta2* theta) - rA + rAB)
    res(2) = r*wA*(-beta1*beta2*rAB*(r - rA)*sin(theta)*sin(beta2*theta) + (beta1*rAB *cos(beta2 &
        *theta) - rA + rAB)*cos(theta))/(beta1*rAB*cos(beta2* theta) - rA + rAB)
end subroutine uA

! Subroutine uB
subroutine uB(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = r*wB*(-beta1*beta2*rAB*(r - rB)*sin(beta2*theta)*cos(theta) - (beta1*rAB *cos(beta2 &
        *theta) + rAB - rB)*sin(theta))/(beta1*rAB*cos(beta2* theta) + rAB - rB)
    res(2) = r*wB*(-beta1*beta2*rAB*(r - rB)*sin(theta)*sin(beta2*theta) + (beta1*rAB *cos(beta2 &
        *theta) + rAB - rB)*cos(theta))/(beta1*rAB*cos(beta2* theta) + rAB - rB)
end subroutine uB

! Function phiA
function phiA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB/(-alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) + alphaA*log( beta1**2*gamma3*rAB**2 &
        *cos(beta2*theta)**2 + beta1*gamma2*rAB*cos (beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2 &
        *theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) + alphaB*log(gamma1 + gamma2 *rA + gamma3*rA* &
        *2) - alphaB*log(beta1**2*gamma3*rAB**2*cos(beta2 *theta)**2 + beta1*gamma2*rAB*cos(beta2 &
        *theta) + 2.0d0*beta1* gamma3*rAB**2*cos(beta2*theta) + gamma1 + gamma2*rAB + gamma3*rAB **2))
    bA = (alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) - alphaA*log(beta1**2* gamma3*rAB**2*cos(beta2 &
        *theta)**2 + beta1*gamma2*rAB*cos(beta2* theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2*theta) &
        + gamma1 + gamma2*rAB + gamma3*rAB**2) + alphaB*log(beta1**2*gamma3*rAB**2* cos(beta2*theta)* &
        *2 + beta1*gamma2*rAB*cos(beta2*theta) + 2.0d0* beta1*gamma3*rAB**2*cos(beta2*theta) + gamma1 &
        + gamma2*rAB + gamma3*rAB**2))/(alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) - alphaA &
        *log(beta1**2*gamma3*rAB**2*cos(beta2*theta)**2 + beta1* gamma2*rAB*cos(beta2*theta) + 2.0d0 &
        *beta1*gamma3*rAB**2*cos(beta2 *theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) - alphaB &
        *log( gamma1 + gamma2*rA + gamma3*rA**2) + alphaB*log(beta1**2*gamma3* rAB**2*cos(beta2*theta)* &
        *2 + beta1*gamma2*rAB*cos(beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2*theta) + gamma1 &
        + gamma2*rAB + gamma3*rAB**2))
    res = aA*log(gamma1 + gamma2*r + gamma3*r**2) + bA
end function phiA

! Function phiB
function phiB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA/(-alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) + alphaA*log( beta1**2*gamma3*rAB**2 &
        *cos(beta2*theta)**2 + beta1*gamma2*rAB*cos (beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2 &
        *theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) + alphaB*log(gamma1 + gamma2 *rA + gamma3*rA* &
        *2) - alphaB*log(beta1**2*gamma3*rAB**2*cos(beta2 *theta)**2 + beta1*gamma2*rAB*cos(beta2 &
        *theta) + 2.0d0*beta1* gamma3*rAB**2*cos(beta2*theta) + gamma1 + gamma2*rAB + gamma3*rAB **2))
    bB = alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2)/(alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) &
        - alphaA*log(beta1**2*gamma3*rAB**2*cos (beta2*theta)**2 + beta1*gamma2*rAB*cos(beta2*theta) &
        + 2.0d0* beta1*gamma3*rAB**2*cos(beta2*theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) - alphaB &
        *log(gamma1 + gamma2*rA + gamma3*rA**2) + alphaB*log(beta1**2*gamma3*rAB**2*cos(beta2*theta)* &
        *2 + beta1* gamma2*rAB*cos(beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2 *theta) + gamma1 &
        + gamma2*rAB + gamma3*rAB**2))
    res = aB*log(gamma1 + gamma2*r + gamma3*r**2) + bB
end function phiB

! Function fA
function fA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB/(-alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) + alphaA*log( beta1**2*gamma3*rAB**2 &
        *cos(beta2*theta)**2 + beta1*gamma2*rAB*cos (beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2 &
        *theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) + alphaB*log(gamma1 + gamma2 *rA + gamma3*rA* &
        *2) - alphaB*log(beta1**2*gamma3*rAB**2*cos(beta2 *theta)**2 + beta1*gamma2*rAB*cos(beta2 &
        *theta) + 2.0d0*beta1* gamma3*rAB**2*cos(beta2*theta) + gamma1 + gamma2*rAB + gamma3*rAB **2))
    bA = (alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) - alphaA*log(beta1**2* gamma3*rAB**2*cos(beta2 &
        *theta)**2 + beta1*gamma2*rAB*cos(beta2* theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2*theta) &
        + gamma1 + gamma2*rAB + gamma3*rAB**2) + alphaB*log(beta1**2*gamma3*rAB**2* cos(beta2*theta)* &
        *2 + beta1*gamma2*rAB*cos(beta2*theta) + 2.0d0* beta1*gamma3*rAB**2*cos(beta2*theta) + gamma1 &
        + gamma2*rAB + gamma3*rAB**2))/(alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) - alphaA &
        *log(beta1**2*gamma3*rAB**2*cos(beta2*theta)**2 + beta1* gamma2*rAB*cos(beta2*theta) + 2.0d0 &
        *beta1*gamma3*rAB**2*cos(beta2 *theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) - alphaB &
        *log( gamma1 + gamma2*rA + gamma3*rA**2) + alphaB*log(beta1**2*gamma3* rAB**2*cos(beta2*theta)* &
        *2 + beta1*gamma2*rAB*cos(beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2*theta) + gamma1 &
        + gamma2*rAB + gamma3*rAB**2))
    res = aA*(alphaA*(rA - rAB*(beta1*cos(beta2*theta) + 1))*(r*(gamma2 + 2*gamma3 *r)**2 - (gamma2 + 4 &
        *gamma3*r)*(gamma1 + gamma2*r + gamma3*r**2 )) + beta1*beta2*r**2*rAB*wA*(gamma2 + 2 &
        *gamma3*r)*(r - rA)*( gamma1 + gamma2*r + gamma3*r**2)*sin(beta2*theta))/(r*(rA - rAB &
        *( beta1*cos(beta2*theta) + 1))*(gamma1 + gamma2*r + gamma3*r**2)**2 )
end function fA

! Function fB
function fB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA/(-alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) + alphaA*log( beta1**2*gamma3*rAB**2 &
        *cos(beta2*theta)**2 + beta1*gamma2*rAB*cos (beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2 &
        *theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) + alphaB*log(gamma1 + gamma2 *rA + gamma3*rA* &
        *2) - alphaB*log(beta1**2*gamma3*rAB**2*cos(beta2 *theta)**2 + beta1*gamma2*rAB*cos(beta2 &
        *theta) + 2.0d0*beta1* gamma3*rAB**2*cos(beta2*theta) + gamma1 + gamma2*rAB + gamma3*rAB **2))
    bB = alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2)/(alphaA*log(gamma1 + gamma2*rB + gamma3*rB**2) &
        - alphaA*log(beta1**2*gamma3*rAB**2*cos (beta2*theta)**2 + beta1*gamma2*rAB*cos(beta2*theta) &
        + 2.0d0* beta1*gamma3*rAB**2*cos(beta2*theta) + gamma1 + gamma2*rAB + gamma3*rAB**2) - alphaB &
        *log(gamma1 + gamma2*rA + gamma3*rA**2) + alphaB*log(beta1**2*gamma3*rAB**2*cos(beta2*theta)* &
        *2 + beta1* gamma2*rAB*cos(beta2*theta) + 2.0d0*beta1*gamma3*rAB**2*cos(beta2 *theta) + gamma1 &
        + gamma2*rAB + gamma3*rAB**2))
    res = aB*(alphaB*(r*(gamma2 + 2*gamma3*r)**2 - (gamma2 + 4*gamma3*r)*(gamma1 + gamma2*r + gamma3*r* &
        *2))*(beta1*rAB*cos(beta2*theta) + rAB - rB) - beta1*beta2*r**2*rAB*wB*(gamma2 + 2 &
        *gamma3*r)*(r - rB)*(gamma1 + gamma2*r + gamma3*r**2)*sin(beta2*theta))/(r*(gamma1 &
        + gamma2*r + gamma3*r**2)**2*(beta1*rAB*cos(beta2*theta) + rAB - rB))
end function fB

end module cht_02
