// Auto-generated by generate_code.py
double aA(double r, double theta, double kA, double kB, double wA, double wB, double nA, double nB, double rA, double rAB, double rB) {
    return -kB/log(pow(rA, -kB)*pow(rAB, kA + kB)*pow(rB, -kA));
}
