% Auto-generated by generate_code.py
function res = aB(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB)
    res = kA.*cos(nA.*theta)./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)). ...
        *cos(nB.*theta));
end
