# Auto-generated by generate_code.py
import numpy as _np
def aB(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB):
    return kA*math.cos(nA*theta)/(math.log(rA**(-kB)*rAB**(kA + kB)*rB**( \
        -kA))*math.cos(nB*theta))
