% Auto-generated by generate_code.py
function res = bA(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB)
    res = log(rAB.^(kA + kB).*rB.^(-kA))./log(rA.^(-kB).*rAB.^(kA + kB). ...
        *rB.^(-kA));
end
