# Auto-generated by generate_code.py
import numpy as _np
def bA(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB):
    return math.log(rAB**(kA + kB)*rB**(-kA))/math.log(rA**(-kB)*rAB**(kA \
        + kB)*rB**(-kA))
