// Auto-generated by generate_code.py

double rAB = 0.75;
double rB = 0.5;
double kA = 2.0;
double kB = 1.0;
double nA = 4;
double nB = 4;
double wA = 1.0;
double wB = -1.0;

double phiA(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = -kB/log(pow(rA, -kB)*pow(rAB, kA + kB)*pow(rB, -kA));
    double bA = log(pow(rAB, kA + kB)*pow(rB, -kA))/log(pow(rA, -kB) \
        *pow(rAB, kA + kB)*pow(rB, -kA));
    return (aA*log(r) + bA)*cos(nA*theta);
}

double phiB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aB = kA*cos(nA*theta)/(log(pow(rA, -kB)*pow(rAB, kA + kB) \
        *pow(rB, -kA))*cos(nB*theta));
    double bB = -log(pow(rB, kA*cos(nA*theta)))/(log(pow(rA, -kB) \
        *pow(rAB, kA + kB)*pow(rB, -kA))*cos(nB*theta));
    return (aB*log(r) + bB)*cos(nB*theta);
}

double fA(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = -kB/log(pow(rA, -kB)*pow(rAB, kA + kB)*pow(rB, -kA));
    double bA = log(pow(rAB, kA + kB)*pow(rB, -kA))/log(pow(rA, -kB) \
        *pow(rAB, kA + kB)*pow(rB, -kA));
    return nA*(aA*log(r) + bA)*(kA*nA*cos(nA*theta) - pow(r, 2)*wA*sin(nA \
*theta))/pow(r, 2);
}

double fB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aB = kA*cos(nA*theta)/(log(pow(rA, -kB)*pow(rAB, kA + kB) \
        *pow(rB, -kA))*cos(nB*theta));
    double bB = -log(pow(rB, kA*cos(nA*theta)))/(log(pow(rA, -kB) \
        *pow(rAB, kA + kB)*pow(rB, -kA))*cos(nB*theta));
    return nB*(aB*log(r) + bB)*(kB*nB*cos(nB*theta) - pow(r, 2)*wB*sin(nB \
*theta))/pow(r, 2);
}
