% Auto-generated by generate_code.py

% Global variables
global rA = 1.0;
global rAB = 0.75;
global rB = 0.5;
global kA = 2.0;
global kB = 1.0;
global nA = 4;
global nB = 4;
global wA = 1.0;
global wB = -1.0;

% Function uA
function res = uA(x, y)
    global rA;
    global rAB;
    global rB;
    global kA;
    global kB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res(1) = -r.*wA.*sin(theta);
    res(2) = r.*wA.*cos(theta);
end

% Function uB
function res = uB(x, y)
    global rA;
    global rAB;
    global rB;
    global kA;
    global kB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res(1) = -r.*wB.*sin(theta);
    res(2) = r.*wB.*cos(theta);
end

% Function phiA
function res = phiA(x, y)
    global rA;
    global rAB;
    global rB;
    global kA;
    global kB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = -kB./log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
    bA = log(rAB.^(kA + kB).*rB.^(-kA))./log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
    res = (aA.*log(r) + bA).*cos(nA.*theta);
end

% Function phiB
function res = phiB(x, y)
    global rA;
    global rAB;
    global rB;
    global kA;
    global kB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = kA.*cos(nA.*theta)./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)).*cos(nB.*theta));
    bB = -log(rB.^(kA.*cos(nA.*theta)))./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)).*cos(nB.*theta));
    res = (aB.*log(r) + bB).*cos(nB.*theta);
end

% Function fA
function res = fA(x, y)
    global rA;
    global rAB;
    global rB;
    global kA;
    global kB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = -kB./log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
    bA = log(rAB.^(kA + kB).*rB.^(-kA))./log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
    res = nA.*(aA.*log(r) + bA).*(kA.*nA.*cos(nA.*theta) - r.^2.*wA.*sin(nA.*theta))./r.^2;
end

% Function fB
function res = fB(x, y)
    global rA;
    global rAB;
    global rB;
    global kA;
    global kB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = kA.*cos(nA.*theta)./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)).*cos(nB.*theta));
    bB = -log(rB.^(kA.*cos(nA.*theta)))./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)).*cos(nB.*theta));
    res = nB.*(aB.*log(r) + bB).*(kB.*nB.*cos(nB.*theta) - r.^2.*wB.*sin(nB.*theta))./r.^2;
end
