% Auto-generated by generate_code.py

rAB = 0.75;
rB = 0.5;
kA = 2.0;
kB = 1.0;
nA = 4;
nB = 4;
wA = 1.0;
wB = -1.0;

function res = phiA(x, y)
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = -kB./log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
    bA = log(rAB.^(kA + kB).*rB.^(-kA))./log(rA.^(-kB).*rAB.^(kA + kB). ...
        *rB.^(-kA));
    res = (aA.*log(r) + bA).*cos(nA.*theta);
end

function res = phiB(x, y)
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = kA.*cos(nA.*theta)./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)). ...
        *cos(nB.*theta));
    bB = -log(rB.^(kA.*cos(nA.*theta)))./(log(rA.^(-kB).*rAB.^(kA + kB). ...
        *rB.^(-kA)).*cos(nB.*theta));
    res = (aB.*log(r) + bB).*cos(nB.*theta);
end

function res = fA(x, y)
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = -kB./log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
    bA = log(rAB.^(kA + kB).*rB.^(-kA))./log(rA.^(-kB).*rAB.^(kA + kB). ...
        *rB.^(-kA));
    res = nA.*(aA.*log(r) + bA).*(kA.*nA.*cos(nA.*theta) - r.^2.*wA. ...
        *sin(nA.*theta))./r.^2;
end

function res = fB(x, y)
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = kA.*cos(nA.*theta)./(log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)). ...
        *cos(nB.*theta));
    bB = -log(rB.^(kA.*cos(nA.*theta)))./(log(rA.^(-kB).*rAB.^(kA + kB). ...
        *rB.^(-kA)).*cos(nB.*theta));
    res = nB.*(aB.*log(r) + bB).*(kB.*nB.*cos(nB.*theta) - r.^2.*wB. ...
        *sin(nB.*theta))./r.^2;
end
