# Auto-generated by generate_code.py

rAB = 0.75
rB = 0.5
kA = 2.0
kB = 1.0
nA = 4
nB = 4
wA = 1.0
wB = -1.0

def phiA(x, y):
    r = math.sqrt(x**2 + y**2)
    theta = math.atan2(y, x)
    aA = -kB/math.log(rA**(-kB)*rAB**(kA + kB)*rB**(-kA))
    bA = math.log(rAB**(kA + kB)*rB**(-kA))/math.log(rA**(-kB)*rAB**(kA
        + kB)*rB**(-kA))
    return (aA*math.log(r) + bA)*math.cos(nA*theta)

def phiB(x, y):
    r = math.sqrt(x**2 + y**2)
    theta = math.atan2(y, x)
    aB = kA*math.cos(nA*theta)/(math.log(rA**(-kB)*rAB**(kA + kB)*rB**(
        -kA))*math.cos(nB*theta))
    bB = -math.log(rB**(kA*math.cos(nA*theta)))/(math.log(rA**(-kB)*rAB*
        *(kA + kB)*rB**(-kA))*math.cos(nB*theta))
    return (aB*math.log(r) + bB)*math.cos(nB*theta)

def fA(x, y):
    r = math.sqrt(x**2 + y**2)
    theta = math.atan2(y, x)
    aA = -kB/math.log(rA**(-kB)*rAB**(kA + kB)*rB**(-kA))
    bA = math.log(rAB**(kA + kB)*rB**(-kA))/math.log(rA**(-kB)*rAB**(kA
        + kB)*rB**(-kA))
    return nA*(aA*math.log(r) + bA)*(kA*nA*math.cos(nA*theta) - r**2*wA
        *math.sin(nA*theta))/r**2

def fB(x, y):
    r = math.sqrt(x**2 + y**2)
    theta = math.atan2(y, x)
    aB = kA*math.cos(nA*theta)/(math.log(rA**(-kB)*rAB**(kA + kB)*rB**(
        -kA))*math.cos(nB*theta))
    bB = -math.log(rB**(kA*math.cos(nA*theta)))/(math.log(rA**(-kB)*rAB*
        *(kA + kB)*rB**(-kA))*math.cos(nB*theta))
    return nB*(aB*math.log(r) + bB)*(kB*nB*math.cos(nB*theta) - r**2*wB
        *math.sin(nB*theta))/r**2
