! Auto-generated by generate_code.py

real(8), parameter :: rAB = 0.75
real(8), parameter :: rB = 0.5
real(8), parameter :: kA = 2.0
real(8), parameter :: kB = 1.0
real(8), parameter :: nA = 4
real(8), parameter :: nB = 4
real(8), parameter :: wA = 1.0
real(8), parameter :: wB = -1.0

function phiA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: r = sqrt(x**2 + y**2)
    real(8) :: theta = atan2(y, x)
    real(8) :: aA = -kB/log(rA**(-kB)*rAB**(kA + kB)*rB**(-kA))
    real(8) :: bA = log(rAB**(kA + kB)*rB**(-kA))/log(rA**(-kB)*rAB**(kA &
        + kB)*rB**(-kA))
    real(8) :: res
    res = (aA*log(r) + bA)*cos(nA*theta)
end function phiA

function phiB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: r = sqrt(x**2 + y**2)
    real(8) :: theta = atan2(y, x)
    real(8) :: aB = kA*cos(nA*theta)/(log(rA**(-kB)*rAB**(kA + kB)*rB**( &
        -kA))*cos(nB*theta))
    real(8) :: bB = -log(rB**(kA*cos(nA*theta)))/(log(rA**(-kB)*rAB**(kA &
        + kB)*rB**(-kA))* cos(nB*theta))
    real(8) :: res
    res = (aB*log(r) + bB)*cos(nB*theta)
end function phiB

function fA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: r = sqrt(x**2 + y**2)
    real(8) :: theta = atan2(y, x)
    real(8) :: aA = -kB/log(rA**(-kB)*rAB**(kA + kB)*rB**(-kA))
    real(8) :: bA = log(rAB**(kA + kB)*rB**(-kA))/log(rA**(-kB)*rAB**(kA &
        + kB)*rB**(-kA))
    real(8) :: res
    res = nA*(aA*log(r) + bA)*(kA*nA*cos(nA*theta) - r**2*wA*sin(nA*theta)) &
        /r**2
end function fA

function fB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: r = sqrt(x**2 + y**2)
    real(8) :: theta = atan2(y, x)
    real(8) :: aB = kA*cos(nA*theta)/(log(rA**(-kB)*rAB**(kA + kB)*rB**( &
        -kA))*cos(nB*theta))
    real(8) :: bB = -log(rB**(kA*cos(nA*theta)))/(log(rA**(-kB)*rAB**(kA &
        + kB)*rB**(-kA))* cos(nB*theta))
    real(8) :: res
    res = nB*(aB*log(r) + bB)*(kB*nB*cos(nB*theta) - r**2*wB*sin(nB*theta)) &
        /r**2
end function fB
