// Auto-generated by generate_code.py
double fA(double r, double theta, double kA, double kB, double wA, double wB, double nA, double nB, double rA, double rAB, double rB) {
    return log(pow(rAB, nA*(kA + kB)*(kA*nA*cos(nA*theta) - pow(r, 2)*wA \
        *sin(nA*theta))/pow(r, 2))*pow(pow(r, kB)*pow(rB, kA), -nA \
        *(kA*nA*cos(nA*theta) - pow(r, 2)*wA*sin(nA*theta)) \
        /pow(r, 2)))/log(pow(rA, -kB)*pow(rAB, kA + kB)*pow(rB, \
        -kA));
}
