! Auto-generated by generate_code.py
function fA(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB) result(res)
    real(8), intent(in) :: r
    real(8), intent(in) :: theta
    real(8), intent(in) :: kA
    real(8), intent(in) :: kB
    real(8), intent(in) :: wA
    real(8), intent(in) :: wB
    real(8), intent(in) :: nA
    real(8), intent(in) :: nB
    real(8), intent(in) :: rA
    real(8), intent(in) :: rAB
    real(8), intent(in) :: rB
    real(8) :: res
    res = log(rAB**(nA*(kA + kB)*(kA*nA*cos(nA*theta) - r**2*wA*sin(nA &
        *theta))/r** 2)*(r**kB*rB**kA)**(-nA*(kA*nA*cos(nA*theta) &
        - r**2*wA*sin(nA* theta))/r**2))/log(rA**(-kB)*rAB**(kA &
        + kB)*rB**(-kA))
end function fA
