# Auto-generated by generate_code.py
import numpy as _np
def fA(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB):
    return math.log(rAB**(nA*(kA + kB)*(kA*nA*math.cos(nA*theta) - r**2*wA \
        *math.sin(nA*theta))/r**2)*(r**kB*rB**kA)**(-nA*(kA*nA \
        *math.cos(nA*theta) - r**2*wA*math.sin(nA*theta))/r**2)) \
        /math.log(rA**(-kB)*rAB**(kA + kB)*rB**(-kA))
