// Auto-generated by generate_code.py
double fB(double r, double theta, double kA, double kB, double wA, double wB, double nA, double nB, double rA, double rAB, double rB) {
    return log(pow(r, kA*nA*(kB*nA*cos(nA*theta)/pow(r, 2) - wB*sin(nA \
        *theta)))*pow(rB, kA*nA*(-kB*nA*cos(nA*theta)/pow(r, 2) \
        + wB*sin(nA*theta))))/log(pow(rA, -kB)*pow(rAB, kA + kB) \
        *pow(rB, -kA));
}
