! Auto-generated by generate_code.py
function fB(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB) result(res)
    real(8), intent(in) :: r
    real(8), intent(in) :: theta
    real(8), intent(in) :: kA
    real(8), intent(in) :: kB
    real(8), intent(in) :: wA
    real(8), intent(in) :: wB
    real(8), intent(in) :: nA
    real(8), intent(in) :: nB
    real(8), intent(in) :: rA
    real(8), intent(in) :: rAB
    real(8), intent(in) :: rB
    real(8) :: res
    res = log(r**(kA*nA*(kB*nA*cos(nA*theta)/r**2 - wB*sin(nA*theta)))*rB* &
        *(kA*nA* (-kB*nA*cos(nA*theta)/r**2 + wB*sin(nA*theta)))) &
        /log(rA**(-kB)* rAB**(kA + kB)*rB**(-kA))
end function fB
