# Auto-generated by generate_code.py
import numpy as _np
def fB(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB):
    return math.log(r**(kA*nA*(kB*nA*math.cos(nA*theta)/r**2 - wB \
        *math.sin(nA*theta)))*rB**(kA*nA*(-kB*nA*math.cos(nA*theta) \
        /r**2 + wB*math.sin(nA*theta))))/math.log(rA**(-kB)*rAB* \
        *(kA + kB)*rB**(-kA))
