# Auto-generated by generate_code.py
import numpy as _np
def phiA(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB):
    return math.log((r**(-kB)*rAB**(kA + kB)*rB**(-kA))**math.cos(nA \
        *theta))/math.log(rA**(-kB)*rAB**(kA + kB)*rB**(-kA))
