% Auto-generated by generate_code.py
function res = phiA(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB)
    res = log((r.^(-kB).*rAB.^(kA + kB).*rB.^(-kA)).^cos(nA.*theta)). ...
        /log(rA.^(-kB).*rAB.^(kA + kB).*rB.^(-kA));
end
