% Auto-generated by generate_code.py
function res = phiB(r, theta, kA, kB, wA, wB, nA, nB, rA, rAB, rB)
    res = log((r./rB).^(kA.*cos(nA.*theta)))./log(rA.^(-kB).*rAB.^(kA ...
        + kB).*rB.^(-kA));
end
