// Auto-generated by generate_code.py

#ifndef CHT_03_H

#define CHT_03_H

#include <cmath>

// Global constants
double rA = 1.0;
double rAB = 0.75;
double rB = 0.5;
double alphaA = 2.0;
double alphaB = 1.0;
double wA = 1.0;
double wB = -1.0;
double h = 1.0;
double n = 4.0;

// Function uA
inline void uA(double x, double y, double res[2]) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    res[0] = -r*wA*sin(theta);
    res[1] = r*wA*cos(theta);
}

// Function uB
inline void uB(double x, double y, double res[2]) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    res[0] = -r*wB*sin(theta);
    res[1] = r*wB*cos(theta);
}

// Function phiA
inline double phiA(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h*rAB*log(rAB)) \
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB \
        *h*rAB*log(rAB));
    double res = (aA*log(r) + bA)*cos(n*theta);
    return res;
}

// Function phiB
inline double phiB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) \
        + alphaB*h*rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double res = (aB*log(r) + bB)*cos(n*theta);
    return res;
}

// Function fA
inline double fA(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h*rAB*log(rAB)) \
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB \
        *h*rAB*log(rAB));
    double res = -n*(aA*log(r) + bA)*(-alphaA*n*cos(n*theta) + pow(r, 2)*wA*sin(n*theta))/pow(r, 2);
    return res;
}

// Function fB
inline double fB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) \
        + alphaB*h*rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double res = -n*(aB*log(r) + bB)*(-alphaB*n*cos(n*theta) + pow(r, 2)*wB*sin(n*theta))/pow(r, 2);
    return res;
}

#endif
