% Auto-generated by generate_code.py

% Global constants
global rA = 1.0;
global rAB = 0.75;
global rB = 0.5;
global alphaA = 2.0;
global alphaB = 1.0;
global wA = 1.0;
global wB = -1.0;
global h = 1.0;
global n = 4.0;

% Function uA
function res = uA(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global wA;
    global wB;
    global h;
    global n;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res = zeros(2,1);
    res(1) = -r.*wA.*sin(theta);
    res(2) = r.*wA.*cos(theta);
end

% Function uB
function res = uB(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global wA;
    global wB;
    global h;
    global n;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res = zeros(2,1);
    res(1) = -r.*wB.*sin(theta);
    res(2) = r.*wB.*cos(theta);
end

% Function phiA
function res = phiA(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global wA;
    global wB;
    global h;
    global n;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = alphaB.*h.*rAB./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) + alphaB. ...
        *h.*rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    bA = (alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) - alphaB.*h.*rAB. ...
        *log(rAB))./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) + alphaB.*h. ...
        *rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    res = (aA.*log(r) + bA).*cos(n.*theta);
end

% Function phiB
function res = phiB(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global wA;
    global wB;
    global h;
    global n;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = alphaA.*h.*rAB./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) + alphaB. ...
        *h.*rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    bB = -alphaA.*h.*rAB.*log(rB)./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB. ...
        *log(rB) + alphaB.*h.*rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    res = (aB.*log(r) + bB).*cos(n.*theta);
end

% Function fA
function res = fA(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global wA;
    global wB;
    global h;
    global n;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = alphaB.*h.*rAB./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) + alphaB. ...
        *h.*rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    bA = (alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) - alphaB.*h.*rAB. ...
        *log(rAB))./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) + alphaB.*h. ...
        *rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    res = -n.*(aA.*log(r) + bA).*(-alphaA.*n.*cos(n.*theta) + r.^2.*wA.*sin(n.*theta))./r.^2;
end

% Function fB
function res = fB(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global wA;
    global wB;
    global h;
    global n;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = alphaA.*h.*rAB./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB.*log(rB) + alphaB. ...
        *h.*rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    bB = -alphaA.*h.*rAB.*log(rB)./(alphaA.*alphaB + alphaA.*h.*rAB.*log(rAB) - alphaA.*h.*rAB. ...
        *log(rB) + alphaB.*h.*rAB.*log(rA) - alphaB.*h.*rAB.*log(rAB));
    res = -n.*(aB.*log(r) + bB).*(-alphaB.*n.*cos(n.*theta) + r.^2.*wB.*sin(n.*theta))./r.^2;
end
