! Auto-generated by generate_code.py

module cht_01

implicit none

! Global constants
real(8), parameter :: rA = 1.0
real(8), parameter :: rAB = 0.75
real(8), parameter :: rB = 0.5
real(8), parameter :: alphaA = 2.0
real(8), parameter :: alphaB = 1.0
real(8), parameter :: wA = 1.0
real(8), parameter :: wB = -1.0
real(8), parameter :: n = 4.0

contains

! Subroutine uA
subroutine uA(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = -r*wA*sin(theta)
    res(2) = r*wA*cos(theta)
end subroutine uA

! Subroutine uB
subroutine uB(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = -r*wB*sin(theta)
    res(2) = r*wB*cos(theta)
end subroutine uB

! Function phiA
function phiA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB/(alphaA*log(rAB) - alphaA*log(rB) + alphaB*log(rA) - alphaB*log( rAB))
    bA = (alphaA*log(rAB) - alphaA*log(rB) - alphaB*log(rAB))/(alphaA*log(rAB) - alphaA*log(rB) &
        + alphaB*log(rA) - alphaB*log(rAB))
    res = (aA*log(r) + bA)*cos(n*theta)
end function phiA

! Function phiB
function phiB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA/(alphaA*log(rAB) - alphaA*log(rB) + alphaB*log(rA) - alphaB*log( rAB))
    bB = -alphaA*log(rB)/(alphaA*log(rAB) - alphaA*log(rB) + alphaB*log(rA) - alphaB*log(rAB))
    res = (aB*log(r) + bB)*cos(n*theta)
end function phiB

! Function fA
function fA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB/(alphaA*log(rAB) - alphaA*log(rB) + alphaB*log(rA) - alphaB*log( rAB))
    bA = (alphaA*log(rAB) - alphaA*log(rB) - alphaB*log(rAB))/(alphaA*log(rAB) - alphaA*log(rB) &
        + alphaB*log(rA) - alphaB*log(rAB))
    res = -n*(aA*log(r) + bA)*(-alphaA*n*cos(n*theta) + r**2*wA*sin(n*theta))/r**2
end function fA

! Function fB
function fB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA/(alphaA*log(rAB) - alphaA*log(rB) + alphaB*log(rA) - alphaB*log( rAB))
    bB = -alphaA*log(rB)/(alphaA*log(rAB) - alphaA*log(rB) + alphaB*log(rA) - alphaB*log(rAB))
    res = -n*(aB*log(r) + bB)*(-alphaB*n*cos(n*theta) + r**2*wB*sin(n*theta))/r**2
end function fB

end module cht_01
