! Auto-generated by generate_code.py

module cht_01

implicit none

! Global constants
real(8), parameter :: rA = 1.0
real(8), parameter :: rAB = 0.75
real(8), parameter :: rB = 0.5
real(8), parameter :: alphaA = 2.0
real(8), parameter :: alphaB = 1.0
real(8), parameter :: nA = 4
real(8), parameter :: nB = 4
real(8), parameter :: wA = 1.0
real(8), parameter :: wB = -1.0

contains

! Subroutine uA
subroutine uA(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = -r*wA*sin(theta)
    res(2) = r*wA*cos(theta)
end subroutine uA

! Subroutine uB
subroutine uB(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = -r*wB*sin(theta)
    res(2) = r*wB*cos(theta)
end subroutine uB

! Function phiA
function phiA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = -alphaB/log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**(-alphaA))
    bA = log(rAB**(alphaA + alphaB)*rB**(-alphaA))/log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**( &
        -alphaA))
    res = (aA*log(r) + bA)*cos(nA*theta)
end function phiA

! Function phiB
function phiB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA*cos(nA*theta)/(log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**( -alphaA))*cos(nB*theta))
    bB = -log(rB**(alphaA*cos(nA*theta)))/(log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**(-alphaA)) &
        *cos(nB*theta))
    res = (aB*log(r) + bB)*cos(nB*theta)
end function phiB

! Function fA
function fA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = -alphaB/log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**(-alphaA))
    bA = log(rAB**(alphaA + alphaB)*rB**(-alphaA))/log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**( &
        -alphaA))
    res = nA*(aA*log(r) + bA)*(alphaA*nA*cos(nA*theta) - r**2*wA*sin(nA*theta))/r **2
end function fA

! Function fB
function fB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA*cos(nA*theta)/(log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**( -alphaA))*cos(nB*theta))
    bB = -log(rB**(alphaA*cos(nA*theta)))/(log(rA**(-alphaB)*rAB**(alphaA + alphaB)*rB**(-alphaA)) &
        *cos(nB*theta))
    res = nB*(aB*log(r) + bB)*(alphaB*nB*cos(nB*theta) - r**2*wB*sin(nB*theta))/r **2
end function fB

end module cht_01
