% Auto-generated by generate_code.py

% Global constants
global rA = 1.0;
global rAB = 0.75;
global rB = 0.5;
global alphaA = 2.0;
global alphaB = 1.0;
global nA = 4;
global nB = 4;
global wA = 1.0;
global wB = -1.0;

% Function uA
function res = uA(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res(1) = -r.*wA.*sin(theta);
    res(2) = r.*wA.*cos(theta);
end

% Function uB
function res = uB(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res(1) = -r.*wB.*sin(theta);
    res(2) = r.*wB.*cos(theta);
end

% Function phiA
function res = phiA(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = -alphaB./log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^(-alphaA));
    bA = log(rAB.^(alphaA + alphaB).*rB.^(-alphaA))./log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^( ...
        -alphaA));
    res = (aA.*log(r) + bA).*cos(nA.*theta);
end

% Function phiB
function res = phiB(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = alphaA.*cos(nA.*theta)./(log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^(-alphaA)).*cos(nB. ...
        *theta));
    bB = -log(rB.^(alphaA.*cos(nA.*theta)))./(log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^( ...
        -alphaA)).*cos(nB.*theta));
    res = (aB.*log(r) + bB).*cos(nB.*theta);
end

% Function fA
function res = fA(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aA = -alphaB./log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^(-alphaA));
    bA = log(rAB.^(alphaA + alphaB).*rB.^(-alphaA))./log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^( ...
        -alphaA));
    res = nA.*(aA.*log(r) + bA).*(alphaA.*nA.*cos(nA.*theta) - r.^2.*wA.*sin(nA.*theta))./r.^2;
end

% Function fB
function res = fB(x, y)
    global rA;
    global rAB;
    global rB;
    global alphaA;
    global alphaB;
    global nA;
    global nB;
    global wA;
    global wB;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    aB = alphaA.*cos(nA.*theta)./(log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^(-alphaA)).*cos(nB. ...
        *theta));
    bB = -log(rB.^(alphaA.*cos(nA.*theta)))./(log(rA.^(-alphaB).*rAB.^(alphaA + alphaB).*rB.^( ...
        -alphaA)).*cos(nB.*theta));
    res = nB.*(aB.*log(r) + bB).*(alphaB.*nB.*cos(nB.*theta) - r.^2.*wB.*sin(nB.*theta))./r.^2;
end
