// Auto-generated by generate_code.py

#ifndef CHT_04_H

#define CHT_04_H

#include <cmath>

// Global constants
double rA = 1.0;
double rAB = 0.75;
double rB = 0.5;
double betaAB_1 = 0.04;
double betaAB_2 = 8.0;
double alphaA = 2.0;
double alphaB = 1.0;
double wA = 1.0;
double wB = -1.0;

// Function RAB
inline double RAB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double res = rAB*(betaAB_1*cos(betaAB_2*theta) + 1);
    return res;
}

// Function nAB
inline void nAB(double x, double y, double res[2]) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    res[0] = betaAB_1*betaAB_2*sin(theta)*sin(betaAB_2*theta)/sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2) \
        *pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2)*pow(cos(betaAB_2*theta), 2) + 2*betaAB_1 \
        *cos(betaAB_2*theta) + 1) + (-betaAB_1*cos(betaAB_2*theta) - 1)*cos(theta) \
        /sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2)*pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*cos(betaAB_2*theta) + 1);
    res[1] = -betaAB_1*betaAB_2*sin(betaAB_2*theta)*cos(theta)/sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2) \
        *pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2)*pow(cos(betaAB_2*theta), 2) + 2*betaAB_1 \
        *cos(betaAB_2*theta) + 1) + (-betaAB_1*cos(betaAB_2*theta) - 1)*sin(theta) \
        /sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2)*pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*cos(betaAB_2*theta) + 1);
}

// Function uA
inline void uA(double x, double y, double res[2]) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    res[0] = -r*wA*sin(theta) + (-betaAB_1*betaAB_2*pow(r, 2)*rAB*wA*sin(betaAB_2*theta) + betaAB_1 \
        *betaAB_2*r*rA*rAB*wA*sin(betaAB_2*theta))*cos(theta)/(betaAB_1*rAB*cos(betaAB_2*theta) - rA \
        + rAB);
    res[1] = r*wA*cos(theta) + (-betaAB_1*betaAB_2*pow(r, 2)*rAB*wA*sin(betaAB_2*theta) + betaAB_1 \
        *betaAB_2*r*rA*rAB*wA*sin(betaAB_2*theta))*sin(theta)/(betaAB_1*rAB*cos(betaAB_2*theta) - rA \
        + rAB);
}

// Function uB
inline void uB(double x, double y, double res[2]) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    res[0] = -r*wB*sin(theta) + (-betaAB_1*betaAB_2*pow(r, 2)*rAB*wB*sin(betaAB_2*theta) + betaAB_1 \
        *betaAB_2*r*rAB*rB*wB*sin(betaAB_2*theta))*cos(theta)/(betaAB_1*rAB*cos(betaAB_2*theta) + rAB \
        - rB);
    res[1] = r*wB*cos(theta) + (-betaAB_1*betaAB_2*pow(r, 2)*rAB*wB*sin(betaAB_2*theta) + betaAB_1 \
        *betaAB_2*r*rAB*rB*wB*sin(betaAB_2*theta))*sin(theta)/(betaAB_1*rAB*cos(betaAB_2*theta) + rAB \
        - rB);
}

// Function phiA
inline double phiA(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h*rAB*log(rAB)) \
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB \
        *h*rAB*log(rAB));
    double res = aA*log((pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1 \
        *pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) \
        - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB \
        *rB)/(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB)) + bA;
    return res;
}

// Function phiB
inline double phiB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) \
        + alphaB*h*rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double res = aB*log((pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1 \
        *pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) \
        - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB \
        *rB)/(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB)) + bB;
    return res;
}

// Function fA
inline double fA(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h*rAB*log(rAB)) \
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB \
        *h*rAB*log(rAB));
    double res = -alphaA*((-2*aA*betaAB_1*r*rAB*cos(betaAB_2*theta)/(pow(betaAB_1, 2)*r*pow(rAB, 2) \
        *pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1 \
        *r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB \
        + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB) + aA*r*(-pow(betaAB_1, 2)*pow(rAB, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*r*rAB*cos(betaAB_2*theta) - 2*betaAB_1 \
        *pow(rAB, 2)*cos(betaAB_2*theta) + rA*rAB - rA*rB - pow(rAB, 2) + rAB*rB) \
        *(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - 2*betaAB_1*r*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - rA*rAB + rA*rB \
        + pow(rAB, 2) - rAB*rB)/pow(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) \
        - r*rAB*rB, 2) + aA*(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - 2 \
        *betaAB_1*r*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB)/(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2 \
        *theta), 2) - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2) \
        *cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r \
        *pow(rAB, 2) - r*rAB*rB))/r + (aA*((2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2 \
        *theta) + 2*betaAB_1*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB \
        *rB*sin(betaAB_2*theta))*(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) \
        - r*rAB*rB)/pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA \
        *rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (-2*pow(betaAB_1, 2) \
        *betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2 \
        *pow(r, 2)*rAB*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2 \
        *theta) + betaAB_1*betaAB_2*rA*rAB*rB*sin(betaAB_2*theta))/(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB))*(-2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2 \
        *theta) - 2*betaAB_1*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) + betaAB_1*betaAB_2*rAB \
        *rB*sin(betaAB_2*theta))/(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) \
        - r*rAB*rB) + aA*((2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) \
        *cos(betaAB_2*theta) - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2*betaAB_1 \
        *betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2 \
        *theta))*(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1 \
        *pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) \
        - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB \
        *rB)/pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (-2*pow(betaAB_1, 2) \
        *betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2 \
        *pow(r, 2)*rAB*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2 \
        *theta) + betaAB_1*betaAB_2*rA*rAB*rB*sin(betaAB_2*theta))/(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB))*(2*pow(betaAB_1, 2)*betaAB_2*r*pow(rAB, 2) \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1*betaAB_2*pow(r, 2)*rAB*sin(betaAB_2 \
        *theta) + 2*betaAB_1*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta) - betaAB_1*betaAB_2*rA \
        *rAB*rB*sin(betaAB_2*theta))*(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) \
        - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB) \
        /pow(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2) \
        *rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA \
        *rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB, 2) + aA \
        *((2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) \
        - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2*betaAB_1*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(4 \
        *pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) - 2 \
        *betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 4*betaAB_1*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta)) \
        *(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB \
        *rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB) \
        /pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 3) + 2*(2 \
        *pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) \
        - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2*betaAB_1*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(-2 \
        *pow(betaAB_1, 2)*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) \
        + betaAB_1*betaAB_2*pow(r, 2)*rAB*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r \
        *pow(rAB, 2)*sin(betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB*rB*sin(betaAB_2*theta)) \
        /pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (-2*pow(betaAB_1, 2) \
        *pow(betaAB_2, 2)*pow(rAB, 2)*pow(sin(betaAB_2*theta), 2) + 2*pow(betaAB_1, 2) \
        *pow(betaAB_2, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(betaAB_2, 2) \
        *rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(betaAB_2, 2)*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*pow(betaAB_2, 2)*rAB*rB*cos(betaAB_2*theta))*(pow(betaAB_1, 2)*r \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) \
        + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2 \
        *theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB)/pow(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (2*pow(betaAB_1, 2)*pow(betaAB_2, 2)*r \
        *pow(rAB, 2)*pow(sin(betaAB_2*theta), 2) - 2*pow(betaAB_1, 2)*pow(betaAB_2, 2)*r \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) + betaAB_1*pow(betaAB_2, 2)*pow(r, 2)*rAB \
        *cos(betaAB_2*theta) - 2*betaAB_1*pow(betaAB_2, 2)*r*pow(rAB, 2)*cos(betaAB_2*theta) \
        + betaAB_1*pow(betaAB_2, 2)*rA*rAB*rB*cos(betaAB_2*theta))/(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB))*(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2 \
        *theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB) \
        /(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB \
        *rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB))/pow(r, 2)) \
        + (aA*pow(betaAB_1, 4)*betaAB_2*pow(r, 2)*pow(rAB, 4)*wA*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 3) - aA*pow(betaAB_1, 4)*betaAB_2*r*rA*pow(rAB, 4)*wA \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 3) - 2*aA*pow(betaAB_1, 3)*betaAB_2 \
        *pow(r, 3)*pow(rAB, 3)*wA*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) + 2*aA \
        *pow(betaAB_1, 3)*betaAB_2*pow(r, 2)*rA*pow(rAB, 3)*wA*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 2) + 3*aA*pow(betaAB_1, 3)*betaAB_2*pow(r, 2)*pow(rAB, 4)*wA \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - aA*pow(betaAB_1, 3)*betaAB_2 \
        *pow(r, 2)*pow(rAB, 3)*rB*wA*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) + aA \
        *pow(betaAB_1, 3)*betaAB_2*pow(r, 2)*pow(rAB, 3)*wA*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 2) - 3*aA*pow(betaAB_1, 3)*betaAB_2*r*rA*pow(rAB, 4)*wA \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) + aA*pow(betaAB_1, 3)*betaAB_2*r*rA \
        *pow(rAB, 3)*rB*wA*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - aA \
        *pow(betaAB_1, 3)*betaAB_2*r*rA*pow(rAB, 3)*wA*sin(betaAB_2*theta)*pow(cos(betaAB_2 \
        *theta), 2) - aA*pow(betaAB_1, 3)*betaAB_2*r*pow(rAB, 3)*rB*wA*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 2) + aA*pow(betaAB_1, 3)*betaAB_2*rA*pow(rAB, 3)*rB*wA \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - 2*aA*pow(betaAB_1, 2)*betaAB_2 \
        *pow(r, 3)*pow(rAB, 3)*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta) + 2*aA \
        *pow(betaAB_1, 2)*betaAB_2*pow(r, 3)*pow(rAB, 2)*rB*wA*sin(betaAB_2*theta)*cos(betaAB_2 \
        *theta) + aA*pow(betaAB_1, 2)*betaAB_2*pow(r, 2)*rA*pow(rAB, 3)*wA*sin(betaAB_2*theta) \
        *cos(betaAB_2*theta) - aA*pow(betaAB_1, 2)*betaAB_2*pow(r, 2)*rA*pow(rAB, 2)*rB*wA \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + 3*aA*pow(betaAB_1, 2)*betaAB_2*pow(r, 2) \
        *pow(rAB, 4)*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta) - 3*aA*pow(betaAB_1, 2) \
        *betaAB_2*pow(r, 2)*pow(rAB, 3)*rB*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta) + aA \
        *pow(betaAB_1, 2)*betaAB_2*r*pow(rA, 2)*pow(rAB, 3)*wA*sin(betaAB_2*theta)*cos(betaAB_2 \
        *theta) - aA*pow(betaAB_1, 2)*betaAB_2*r*pow(rA, 2)*pow(rAB, 2)*rB*wA*sin(betaAB_2 \
        *theta)*cos(betaAB_2*theta) - 3*aA*pow(betaAB_1, 2)*betaAB_2*r*rA*pow(rAB, 4)*wA \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + 3*aA*pow(betaAB_1, 2)*betaAB_2*r*rA \
        *pow(rAB, 3)*rB*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta) - aA*betaAB_1*betaAB_2 \
        *pow(r, 2)*rA*pow(rAB, 3)*wA*sin(betaAB_2*theta) + 2*aA*betaAB_1*betaAB_2*pow(r, 2)*rA \
        *pow(rAB, 2)*rB*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*pow(r, 2)*rA*pow(rAB, 2) \
        *wA*sin(betaAB_2*theta) - aA*betaAB_1*betaAB_2*pow(r, 2)*rA*rAB*pow(rB, 2)*wA \
        *sin(betaAB_2*theta) - aA*betaAB_1*betaAB_2*pow(r, 2)*rA*rAB*rB*wA*sin(betaAB_2*theta) \
        + aA*betaAB_1*betaAB_2*pow(r, 2)*pow(rAB, 4)*wA*sin(betaAB_2*theta) - 2*aA*betaAB_1 \
        *betaAB_2*pow(r, 2)*pow(rAB, 3)*rB*wA*sin(betaAB_2*theta) - aA*betaAB_1*betaAB_2 \
        *pow(r, 2)*pow(rAB, 3)*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*pow(r, 2) \
        *pow(rAB, 2)*pow(rB, 2)*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*pow(r, 2) \
        *pow(rAB, 2)*rB*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*r*pow(rA, 2)*pow(rAB, 3) \
        *wA*sin(betaAB_2*theta) - 2*aA*betaAB_1*betaAB_2*r*pow(rA, 2)*pow(rAB, 2)*rB*wA \
        *sin(betaAB_2*theta) - aA*betaAB_1*betaAB_2*r*pow(rA, 2)*pow(rAB, 2)*wA*sin(betaAB_2 \
        *theta) + aA*betaAB_1*betaAB_2*r*pow(rA, 2)*rAB*pow(rB, 2)*wA*sin(betaAB_2*theta) + aA \
        *betaAB_1*betaAB_2*r*pow(rA, 2)*rAB*rB*wA*sin(betaAB_2*theta) - aA*betaAB_1*betaAB_2*r \
        *rA*pow(rAB, 4)*wA*sin(betaAB_2*theta) + 2*aA*betaAB_1*betaAB_2*r*rA*pow(rAB, 3)*rB*wA \
        *sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*r*rA*pow(rAB, 3)*wA*sin(betaAB_2*theta) \
        - aA*betaAB_1*betaAB_2*r*rA*pow(rAB, 2)*pow(rB, 2)*wA*sin(betaAB_2*theta) - 2*aA \
        *betaAB_1*betaAB_2*r*rA*pow(rAB, 2)*rB*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*r \
        *rA*rAB*pow(rB, 2)*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*r*pow(rAB, 3)*rB*wA \
        *sin(betaAB_2*theta) - aA*betaAB_1*betaAB_2*r*pow(rAB, 2)*pow(rB, 2)*wA*sin(betaAB_2 \
        *theta) + aA*betaAB_1*betaAB_2*pow(rA, 2)*pow(rAB, 2)*rB*wA*sin(betaAB_2*theta) - aA \
        *betaAB_1*betaAB_2*pow(rA, 2)*rAB*pow(rB, 2)*wA*sin(betaAB_2*theta) - aA*betaAB_1 \
        *betaAB_2*rA*pow(rAB, 3)*rB*wA*sin(betaAB_2*theta) + aA*betaAB_1*betaAB_2*rA \
        *pow(rAB, 2)*pow(rB, 2)*wA*sin(betaAB_2*theta))/(-pow(betaAB_1, 4)*r*pow(rAB, 4) \
        *pow(cos(betaAB_2*theta), 4) + pow(betaAB_1, 3)*pow(r, 2)*pow(rAB, 3)*pow(cos(betaAB_2 \
        *theta), 3) + pow(betaAB_1, 3)*r*rA*pow(rAB, 3)*pow(cos(betaAB_2*theta), 3) - 4 \
        *pow(betaAB_1, 3)*r*pow(rAB, 4)*pow(cos(betaAB_2*theta), 3) + pow(betaAB_1, 3)*r \
        *pow(rAB, 3)*rB*pow(cos(betaAB_2*theta), 3) + pow(betaAB_1, 3)*rA*pow(rAB, 3)*rB \
        *pow(cos(betaAB_2*theta), 3) - pow(betaAB_1, 2)*pow(r, 2)*rA*pow(rAB, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*pow(betaAB_1, 2)*pow(r, 2)*pow(rAB, 3) \
        *pow(cos(betaAB_2*theta), 2) - pow(betaAB_1, 2)*pow(r, 2)*pow(rAB, 2)*rB \
        *pow(cos(betaAB_2*theta), 2) + 4*pow(betaAB_1, 2)*r*rA*pow(rAB, 3)*pow(cos(betaAB_2 \
        *theta), 2) - 2*pow(betaAB_1, 2)*r*rA*pow(rAB, 2)*rB*pow(cos(betaAB_2*theta), 2) - 6 \
        *pow(betaAB_1, 2)*r*pow(rAB, 4)*pow(cos(betaAB_2*theta), 2) + 4*pow(betaAB_1, 2)*r \
        *pow(rAB, 3)*rB*pow(cos(betaAB_2*theta), 2) - pow(betaAB_1, 2)*pow(rA, 2)*pow(rAB, 2) \
        *rB*pow(cos(betaAB_2*theta), 2) + 2*pow(betaAB_1, 2)*rA*pow(rAB, 3)*rB*pow(cos(betaAB_2 \
        *theta), 2) - pow(betaAB_1, 2)*rA*pow(rAB, 2)*pow(rB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rA*pow(rAB, 2)*cos(betaAB_2*theta) + betaAB_1*pow(r, 2)*rA*rAB*rB \
        *cos(betaAB_2*theta) + betaAB_1*pow(r, 2)*pow(rAB, 3)*cos(betaAB_2*theta) - betaAB_1 \
        *pow(r, 2)*pow(rAB, 2)*rB*cos(betaAB_2*theta) - betaAB_1*r*pow(rA, 2)*pow(rAB, 2) \
        *cos(betaAB_2*theta) + betaAB_1*r*pow(rA, 2)*rAB*rB*cos(betaAB_2*theta) + 5*betaAB_1*r \
        *rA*pow(rAB, 3)*cos(betaAB_2*theta) - 6*betaAB_1*r*rA*pow(rAB, 2)*rB*cos(betaAB_2 \
        *theta) + betaAB_1*r*rA*rAB*pow(rB, 2)*cos(betaAB_2*theta) - 4*betaAB_1*r*pow(rAB, 4) \
        *cos(betaAB_2*theta) + 5*betaAB_1*r*pow(rAB, 3)*rB*cos(betaAB_2*theta) - betaAB_1*r \
        *pow(rAB, 2)*pow(rB, 2)*cos(betaAB_2*theta) - betaAB_1*pow(rA, 2)*pow(rAB, 2)*rB \
        *cos(betaAB_2*theta) + betaAB_1*pow(rA, 2)*rAB*pow(rB, 2)*cos(betaAB_2*theta) \
        + betaAB_1*rA*pow(rAB, 3)*rB*cos(betaAB_2*theta) - betaAB_1*rA*pow(rAB, 2)*pow(rB, 2) \
        *cos(betaAB_2*theta) - r*pow(rA, 2)*pow(rAB, 2) + 2*r*pow(rA, 2)*rAB*rB - r*pow(rA, 2) \
        *pow(rB, 2) + 2*r*rA*pow(rAB, 3) - 4*r*rA*pow(rAB, 2)*rB + 2*r*rA*rAB*pow(rB, 2) - r \
        *pow(rAB, 4) + 2*r*pow(rAB, 3)*rB - r*pow(rAB, 2)*pow(rB, 2));
    return res;
}

// Function fB
inline double fB(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) \
        + alphaB*h*rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double res = -alphaB*((-2*aB*betaAB_1*r*rAB*cos(betaAB_2*theta)/(pow(betaAB_1, 2)*r*pow(rAB, 2) \
        *pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1 \
        *r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB \
        + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB) + aB*r*(-pow(betaAB_1, 2)*pow(rAB, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*r*rAB*cos(betaAB_2*theta) - 2*betaAB_1 \
        *pow(rAB, 2)*cos(betaAB_2*theta) + rA*rAB - rA*rB - pow(rAB, 2) + rAB*rB) \
        *(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - 2*betaAB_1*r*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - rA*rAB + rA*rB \
        + pow(rAB, 2) - rAB*rB)/pow(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) \
        - r*rAB*rB, 2) + aB*(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - 2 \
        *betaAB_1*r*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB)/(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2 \
        *theta), 2) - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2) \
        *cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r \
        *pow(rAB, 2) - r*rAB*rB))/r + (aB*((2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2 \
        *theta) + 2*betaAB_1*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB \
        *rB*sin(betaAB_2*theta))*(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) \
        - r*rAB*rB)/pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA \
        *rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (-2*pow(betaAB_1, 2) \
        *betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2 \
        *pow(r, 2)*rAB*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2 \
        *theta) + betaAB_1*betaAB_2*rA*rAB*rB*sin(betaAB_2*theta))/(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB))*(-2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2 \
        *theta) - 2*betaAB_1*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) + betaAB_1*betaAB_2*rAB \
        *rB*sin(betaAB_2*theta))/(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) \
        - r*rAB*rB) + aB*((2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) \
        *cos(betaAB_2*theta) - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2*betaAB_1 \
        *betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2 \
        *theta))*(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1 \
        *pow(r, 2)*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) \
        - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB \
        *rB)/pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (-2*pow(betaAB_1, 2) \
        *betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2 \
        *pow(r, 2)*rAB*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2 \
        *theta) + betaAB_1*betaAB_2*rA*rAB*rB*sin(betaAB_2*theta))/(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB))*(2*pow(betaAB_1, 2)*betaAB_2*r*pow(rAB, 2) \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1*betaAB_2*pow(r, 2)*rAB*sin(betaAB_2 \
        *theta) + 2*betaAB_1*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta) - betaAB_1*betaAB_2*rA \
        *rAB*rB*sin(betaAB_2*theta))*(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) \
        - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) \
        - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB) \
        /pow(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2) \
        *rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA \
        *rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB, 2) + aB \
        *((2*pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) \
        - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2*betaAB_1*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(4 \
        *pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) - 2 \
        *betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 4*betaAB_1*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta)) \
        *(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB \
        *rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB) \
        /pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 3) + 2*(2 \
        *pow(betaAB_1, 2)*betaAB_2*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) \
        - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2*betaAB_1*betaAB_2*pow(rAB, 2) \
        *sin(betaAB_2*theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(-2 \
        *pow(betaAB_1, 2)*betaAB_2*r*pow(rAB, 2)*sin(betaAB_2*theta)*cos(betaAB_2*theta) \
        + betaAB_1*betaAB_2*pow(r, 2)*rAB*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r \
        *pow(rAB, 2)*sin(betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB*rB*sin(betaAB_2*theta)) \
        /pow(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB \
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (-2*pow(betaAB_1, 2) \
        *pow(betaAB_2, 2)*pow(rAB, 2)*pow(sin(betaAB_2*theta), 2) + 2*pow(betaAB_1, 2) \
        *pow(betaAB_2, 2)*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(betaAB_2, 2) \
        *rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(betaAB_2, 2)*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*pow(betaAB_2, 2)*rAB*rB*cos(betaAB_2*theta))*(pow(betaAB_1, 2)*r \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB*cos(betaAB_2*theta) \
        + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2 \
        *theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB)/pow(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB, 2) + (2*pow(betaAB_1, 2)*pow(betaAB_2, 2)*r \
        *pow(rAB, 2)*pow(sin(betaAB_2*theta), 2) - 2*pow(betaAB_1, 2)*pow(betaAB_2, 2)*r \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) + betaAB_1*pow(betaAB_2, 2)*pow(r, 2)*rAB \
        *cos(betaAB_2*theta) - 2*betaAB_1*pow(betaAB_2, 2)*r*pow(rAB, 2)*cos(betaAB_2*theta) \
        + betaAB_1*pow(betaAB_2, 2)*rA*rAB*rB*cos(betaAB_2*theta))/(pow(betaAB_1, 2) \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2 \
        *betaAB_1*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA \
        *rAB + rA*rB + pow(rAB, 2) - rAB*rB))*(pow(betaAB_1, 2)*pow(rAB, 2)*pow(cos(betaAB_2 \
        *theta), 2) - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + pow(rAB, 2) - rAB*rB) \
        /(pow(betaAB_1, 2)*r*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rAB \
        *cos(betaAB_2*theta) + 2*betaAB_1*r*pow(rAB, 2)*cos(betaAB_2*theta) - betaAB_1*rA*rAB \
        *rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*pow(rAB, 2) - r*rAB*rB))/pow(r, 2)) \
        + (aB*pow(betaAB_1, 4)*betaAB_2*pow(r, 2)*pow(rAB, 4)*wB*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 3) - aB*pow(betaAB_1, 4)*betaAB_2*r*pow(rAB, 4)*rB*wB \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 3) - 2*aB*pow(betaAB_1, 3)*betaAB_2 \
        *pow(r, 3)*pow(rAB, 3)*wB*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - aB \
        *pow(betaAB_1, 3)*betaAB_2*pow(r, 2)*rA*pow(rAB, 3)*wB*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 2) + 3*aB*pow(betaAB_1, 3)*betaAB_2*pow(r, 2)*pow(rAB, 4)*wB \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) + 2*aB*pow(betaAB_1, 3)*betaAB_2 \
        *pow(r, 2)*pow(rAB, 3)*rB*wB*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) + aB \
        *pow(betaAB_1, 3)*betaAB_2*pow(r, 2)*pow(rAB, 3)*wB*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 2) + aB*pow(betaAB_1, 3)*betaAB_2*r*rA*pow(rAB, 3)*rB*wB \
        *sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - aB*pow(betaAB_1, 3)*betaAB_2*r*rA \
        *pow(rAB, 3)*wB*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - 3*aB*pow(betaAB_1, 3) \
        *betaAB_2*r*pow(rAB, 4)*rB*wB*sin(betaAB_2*theta)*pow(cos(betaAB_2*theta), 2) - aB \
        *pow(betaAB_1, 3)*betaAB_2*r*pow(rAB, 3)*rB*wB*sin(betaAB_2*theta)*pow(cos(betaAB_2 \
        *theta), 2) + aB*pow(betaAB_1, 3)*betaAB_2*rA*pow(rAB, 3)*rB*wB*sin(betaAB_2*theta) \
        *pow(cos(betaAB_2*theta), 2) + 2*aB*pow(betaAB_1, 2)*betaAB_2*pow(r, 3)*rA*pow(rAB, 2) \
        *wB*sin(betaAB_2*theta)*cos(betaAB_2*theta) - 2*aB*pow(betaAB_1, 2)*betaAB_2*pow(r, 3) \
        *pow(rAB, 3)*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta) - 3*aB*pow(betaAB_1, 2) \
        *betaAB_2*pow(r, 2)*rA*pow(rAB, 3)*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta) - aB \
        *pow(betaAB_1, 2)*betaAB_2*pow(r, 2)*rA*pow(rAB, 2)*rB*wB*sin(betaAB_2*theta) \
        *cos(betaAB_2*theta) + 3*aB*pow(betaAB_1, 2)*betaAB_2*pow(r, 2)*pow(rAB, 4)*wB \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + aB*pow(betaAB_1, 2)*betaAB_2*pow(r, 2) \
        *pow(rAB, 3)*rB*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta) + 3*aB*pow(betaAB_1, 2) \
        *betaAB_2*r*rA*pow(rAB, 3)*rB*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta) - aB \
        *pow(betaAB_1, 2)*betaAB_2*r*rA*pow(rAB, 2)*pow(rB, 2)*wB*sin(betaAB_2*theta) \
        *cos(betaAB_2*theta) - 3*aB*pow(betaAB_1, 2)*betaAB_2*r*pow(rAB, 4)*rB*wB*sin(betaAB_2 \
        *theta)*cos(betaAB_2*theta) + aB*pow(betaAB_1, 2)*betaAB_2*r*pow(rAB, 3)*pow(rB, 2)*wB \
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + aB*betaAB_1*betaAB_2*pow(r, 2)*pow(rA, 2) \
        *pow(rAB, 2)*wB*sin(betaAB_2*theta) - aB*betaAB_1*betaAB_2*pow(r, 2)*pow(rA, 2)*rAB*rB \
        *wB*sin(betaAB_2*theta) - 2*aB*betaAB_1*betaAB_2*pow(r, 2)*rA*pow(rAB, 3)*wB \
        *sin(betaAB_2*theta) + 2*aB*betaAB_1*betaAB_2*pow(r, 2)*rA*pow(rAB, 2)*rB*wB \
        *sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*pow(r, 2)*rA*pow(rAB, 2)*wB*sin(betaAB_2 \
        *theta) - aB*betaAB_1*betaAB_2*pow(r, 2)*rA*rAB*rB*wB*sin(betaAB_2*theta) + aB*betaAB_1 \
        *betaAB_2*pow(r, 2)*pow(rAB, 4)*wB*sin(betaAB_2*theta) - aB*betaAB_1*betaAB_2*pow(r, 2) \
        *pow(rAB, 3)*rB*wB*sin(betaAB_2*theta) - aB*betaAB_1*betaAB_2*pow(r, 2)*pow(rAB, 3)*wB \
        *sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*pow(r, 2)*pow(rAB, 2)*rB*wB*sin(betaAB_2 \
        *theta) - aB*betaAB_1*betaAB_2*r*pow(rA, 2)*pow(rAB, 2)*rB*wB*sin(betaAB_2*theta) - aB \
        *betaAB_1*betaAB_2*r*pow(rA, 2)*pow(rAB, 2)*wB*sin(betaAB_2*theta) + aB*betaAB_1 \
        *betaAB_2*r*pow(rA, 2)*rAB*pow(rB, 2)*wB*sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*r \
        *pow(rA, 2)*rAB*rB*wB*sin(betaAB_2*theta) + 2*aB*betaAB_1*betaAB_2*r*rA*pow(rAB, 3)*rB \
        *wB*sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*r*rA*pow(rAB, 3)*wB*sin(betaAB_2*theta) \
        - 2*aB*betaAB_1*betaAB_2*r*rA*pow(rAB, 2)*pow(rB, 2)*wB*sin(betaAB_2*theta) - 2*aB \
        *betaAB_1*betaAB_2*r*rA*pow(rAB, 2)*rB*wB*sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*r \
        *rA*rAB*pow(rB, 2)*wB*sin(betaAB_2*theta) - aB*betaAB_1*betaAB_2*r*pow(rAB, 4)*rB*wB \
        *sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*r*pow(rAB, 3)*pow(rB, 2)*wB*sin(betaAB_2 \
        *theta) + aB*betaAB_1*betaAB_2*r*pow(rAB, 3)*rB*wB*sin(betaAB_2*theta) - aB*betaAB_1 \
        *betaAB_2*r*pow(rAB, 2)*pow(rB, 2)*wB*sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2 \
        *pow(rA, 2)*pow(rAB, 2)*rB*wB*sin(betaAB_2*theta) - aB*betaAB_1*betaAB_2*pow(rA, 2)*rAB \
        *pow(rB, 2)*wB*sin(betaAB_2*theta) - aB*betaAB_1*betaAB_2*rA*pow(rAB, 3)*rB*wB \
        *sin(betaAB_2*theta) + aB*betaAB_1*betaAB_2*rA*pow(rAB, 2)*pow(rB, 2)*wB*sin(betaAB_2 \
        *theta))/(-pow(betaAB_1, 4)*r*pow(rAB, 4)*pow(cos(betaAB_2*theta), 4) \
        + pow(betaAB_1, 3)*pow(r, 2)*pow(rAB, 3)*pow(cos(betaAB_2*theta), 3) + pow(betaAB_1, 3) \
        *r*rA*pow(rAB, 3)*pow(cos(betaAB_2*theta), 3) - 4*pow(betaAB_1, 3)*r*pow(rAB, 4) \
        *pow(cos(betaAB_2*theta), 3) + pow(betaAB_1, 3)*r*pow(rAB, 3)*rB*pow(cos(betaAB_2 \
        *theta), 3) + pow(betaAB_1, 3)*rA*pow(rAB, 3)*rB*pow(cos(betaAB_2*theta), 3) \
        - pow(betaAB_1, 2)*pow(r, 2)*rA*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) + 2 \
        *pow(betaAB_1, 2)*pow(r, 2)*pow(rAB, 3)*pow(cos(betaAB_2*theta), 2) - pow(betaAB_1, 2) \
        *pow(r, 2)*pow(rAB, 2)*rB*pow(cos(betaAB_2*theta), 2) + 4*pow(betaAB_1, 2)*r*rA \
        *pow(rAB, 3)*pow(cos(betaAB_2*theta), 2) - 2*pow(betaAB_1, 2)*r*rA*pow(rAB, 2)*rB \
        *pow(cos(betaAB_2*theta), 2) - 6*pow(betaAB_1, 2)*r*pow(rAB, 4)*pow(cos(betaAB_2 \
        *theta), 2) + 4*pow(betaAB_1, 2)*r*pow(rAB, 3)*rB*pow(cos(betaAB_2*theta), 2) \
        - pow(betaAB_1, 2)*pow(rA, 2)*pow(rAB, 2)*rB*pow(cos(betaAB_2*theta), 2) + 2 \
        *pow(betaAB_1, 2)*rA*pow(rAB, 3)*rB*pow(cos(betaAB_2*theta), 2) - pow(betaAB_1, 2)*rA \
        *pow(rAB, 2)*pow(rB, 2)*pow(cos(betaAB_2*theta), 2) - betaAB_1*pow(r, 2)*rA*pow(rAB, 2) \
        *cos(betaAB_2*theta) + betaAB_1*pow(r, 2)*rA*rAB*rB*cos(betaAB_2*theta) + betaAB_1 \
        *pow(r, 2)*pow(rAB, 3)*cos(betaAB_2*theta) - betaAB_1*pow(r, 2)*pow(rAB, 2)*rB \
        *cos(betaAB_2*theta) - betaAB_1*r*pow(rA, 2)*pow(rAB, 2)*cos(betaAB_2*theta) + betaAB_1 \
        *r*pow(rA, 2)*rAB*rB*cos(betaAB_2*theta) + 5*betaAB_1*r*rA*pow(rAB, 3)*cos(betaAB_2 \
        *theta) - 6*betaAB_1*r*rA*pow(rAB, 2)*rB*cos(betaAB_2*theta) + betaAB_1*r*rA*rAB \
        *pow(rB, 2)*cos(betaAB_2*theta) - 4*betaAB_1*r*pow(rAB, 4)*cos(betaAB_2*theta) + 5 \
        *betaAB_1*r*pow(rAB, 3)*rB*cos(betaAB_2*theta) - betaAB_1*r*pow(rAB, 2)*pow(rB, 2) \
        *cos(betaAB_2*theta) - betaAB_1*pow(rA, 2)*pow(rAB, 2)*rB*cos(betaAB_2*theta) \
        + betaAB_1*pow(rA, 2)*rAB*pow(rB, 2)*cos(betaAB_2*theta) + betaAB_1*rA*pow(rAB, 3)*rB \
        *cos(betaAB_2*theta) - betaAB_1*rA*pow(rAB, 2)*pow(rB, 2)*cos(betaAB_2*theta) - r \
        *pow(rA, 2)*pow(rAB, 2) + 2*r*pow(rA, 2)*rAB*rB - r*pow(rA, 2)*pow(rB, 2) + 2*r*rA \
        *pow(rAB, 3) - 4*r*rA*pow(rAB, 2)*rB + 2*r*rA*rAB*pow(rB, 2) - r*pow(rAB, 4) + 2*r \
        *pow(rAB, 3)*rB - r*pow(rAB, 2)*pow(rB, 2));
    return res;
}

// Function H
inline double H(double x, double y) {
    double r = sqrt(pow(x, 2) + pow(y, 2));
    double theta = atan2(y, x);
    double aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h*rAB*log(rAB)) \
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB \
        *h*rAB*log(rAB));
    double aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) + alphaB*h \
        *rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) \
        + alphaB*h*rAB*log(rA) - alphaB*h*rAB*log(rAB));
    double res = (aA*alphaA*pow(betaAB_1, 2)*pow(rAB, 2)*sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2) \
        *pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2)*pow(cos(betaAB_2*theta), 2) + 2 \
        *betaAB_1*cos(betaAB_2*theta) + 1)*pow(cos(betaAB_2*theta), 2) + aA*alphaA*rA*rAB \
        *sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2)*pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*cos(betaAB_2*theta) + 1) - aA*alphaA*rA*rB \
        *sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2)*pow(sin(betaAB_2*theta), 2) + pow(betaAB_1, 2) \
        *pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*cos(betaAB_2*theta) + 1) - aA*alphaA \
        *pow(rAB, 2)*sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2)*pow(sin(betaAB_2*theta), 2) \
        + pow(betaAB_1, 2)*pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*cos(betaAB_2*theta) + 1) \
        + aA*alphaA*rAB*rB*sqrt(pow(betaAB_1, 2)*pow(betaAB_2, 2)*pow(sin(betaAB_2*theta), 2) \
        + pow(betaAB_1, 2)*pow(cos(betaAB_2*theta), 2) + 2*betaAB_1*cos(betaAB_2*theta) + 1)) \
        /(aA*pow(betaAB_1, 3)*pow(rAB, 3)*log(rAB)*pow(cos(betaAB_2*theta), 3) - aA \
        *pow(betaAB_1, 2)*rA*pow(rAB, 2)*log(rAB)*pow(cos(betaAB_2*theta), 2) + 3*aA \
        *pow(betaAB_1, 2)*pow(rAB, 3)*log(rAB)*pow(cos(betaAB_2*theta), 2) - aA \
        *pow(betaAB_1, 2)*pow(rAB, 2)*rB*log(rAB)*pow(cos(betaAB_2*theta), 2) - 2*aA*betaAB_1 \
        *rA*pow(rAB, 2)*log(rAB)*cos(betaAB_2*theta) + aA*betaAB_1*rA*rAB*rB*log(rAB) \
        *cos(betaAB_2*theta) + 3*aA*betaAB_1*pow(rAB, 3)*log(rAB)*cos(betaAB_2*theta) - 2*aA \
        *betaAB_1*pow(rAB, 2)*rB*log(rAB)*cos(betaAB_2*theta) - aA*rA*pow(rAB, 2)*log(rAB) + aA \
        *rA*rAB*rB*log(rAB) + aA*pow(rAB, 3)*log(rAB) - aA*pow(rAB, 2)*rB*log(rAB) - aB \
        *pow(betaAB_1, 3)*pow(rAB, 3)*log(rAB)*pow(cos(betaAB_2*theta), 3) + aB \
        *pow(betaAB_1, 2)*rA*pow(rAB, 2)*log(rAB)*pow(cos(betaAB_2*theta), 2) - 3*aB \
        *pow(betaAB_1, 2)*pow(rAB, 3)*log(rAB)*pow(cos(betaAB_2*theta), 2) + aB \
        *pow(betaAB_1, 2)*pow(rAB, 2)*rB*log(rAB)*pow(cos(betaAB_2*theta), 2) + 2*aB*betaAB_1 \
        *rA*pow(rAB, 2)*log(rAB)*cos(betaAB_2*theta) - aB*betaAB_1*rA*rAB*rB*log(rAB) \
        *cos(betaAB_2*theta) - 3*aB*betaAB_1*pow(rAB, 3)*log(rAB)*cos(betaAB_2*theta) + 2*aB \
        *betaAB_1*pow(rAB, 2)*rB*log(rAB)*cos(betaAB_2*theta) + aB*rA*pow(rAB, 2)*log(rAB) - aB \
        *rA*rAB*rB*log(rAB) - aB*pow(rAB, 3)*log(rAB) + aB*pow(rAB, 2)*rB*log(rAB) + bA \
        *pow(betaAB_1, 3)*pow(rAB, 3)*pow(cos(betaAB_2*theta), 3) - bA*pow(betaAB_1, 2)*rA \
        *pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) + 3*bA*pow(betaAB_1, 2)*pow(rAB, 3) \
        *pow(cos(betaAB_2*theta), 2) - bA*pow(betaAB_1, 2)*pow(rAB, 2)*rB*pow(cos(betaAB_2 \
        *theta), 2) - 2*bA*betaAB_1*rA*pow(rAB, 2)*cos(betaAB_2*theta) + bA*betaAB_1*rA*rAB*rB \
        *cos(betaAB_2*theta) + 3*bA*betaAB_1*pow(rAB, 3)*cos(betaAB_2*theta) - 2*bA*betaAB_1 \
        *pow(rAB, 2)*rB*cos(betaAB_2*theta) - bA*rA*pow(rAB, 2) + bA*rA*rAB*rB + bA \
        *pow(rAB, 3) - bA*pow(rAB, 2)*rB - bB*pow(betaAB_1, 3)*pow(rAB, 3)*pow(cos(betaAB_2 \
        *theta), 3) + bB*pow(betaAB_1, 2)*rA*pow(rAB, 2)*pow(cos(betaAB_2*theta), 2) - 3*bB \
        *pow(betaAB_1, 2)*pow(rAB, 3)*pow(cos(betaAB_2*theta), 2) + bB*pow(betaAB_1, 2) \
        *pow(rAB, 2)*rB*pow(cos(betaAB_2*theta), 2) + 2*bB*betaAB_1*rA*pow(rAB, 2)*cos(betaAB_2 \
        *theta) - bB*betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - 3*bB*betaAB_1*pow(rAB, 3) \
        *cos(betaAB_2*theta) + 2*bB*betaAB_1*pow(rAB, 2)*rB*cos(betaAB_2*theta) + bB*rA \
        *pow(rAB, 2) - bB*rA*rAB*rB - bB*pow(rAB, 3) + bB*pow(rAB, 2)*rB);
    return res;
}

#endif
