! Auto-generated by generate_code.py

module cht_04

implicit none

! Global constants
real(8), parameter :: rA = 1.0
real(8), parameter :: rAB = 0.75
real(8), parameter :: rB = 0.5
real(8), parameter :: betaAB_1 = 0.04
real(8), parameter :: betaAB_2 = 8.0
real(8), parameter :: alphaA = 2.0
real(8), parameter :: alphaB = 1.0
real(8), parameter :: wA = 1.0
real(8), parameter :: wB = -1.0

contains

! Function RAB
function RAB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res = rAB*(betaAB_1*cos(betaAB_2*theta) + 1)
end function RAB

! Subroutine nAB
subroutine nAB(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = betaAB_1*betaAB_2*sin(theta)*sin(betaAB_2*theta)/sqrt(betaAB_1**2* betaAB_2**2 &
        *sin(betaAB_2*theta)**2 + betaAB_1**2*cos(betaAB_2* theta)**2 + 2*betaAB_1*cos(betaAB_2*theta) &
        + 1) + (-betaAB_1*cos( betaAB_2*theta) - 1)*cos(theta)/sqrt(betaAB_1**2*betaAB_2**2 &
        *sin( betaAB_2*theta)**2 + betaAB_1**2*cos(betaAB_2*theta)**2 + 2* betaAB_1*cos(betaAB_2 &
        *theta) + 1)
    res(2) = -betaAB_1*betaAB_2*sin(betaAB_2*theta)*cos(theta)/sqrt(betaAB_1**2* betaAB_2**2 &
        *sin(betaAB_2*theta)**2 + betaAB_1**2*cos(betaAB_2* theta)**2 + 2*betaAB_1*cos(betaAB_2*theta) &
        + 1) + (-betaAB_1*cos( betaAB_2*theta) - 1)*sin(theta)/sqrt(betaAB_1**2*betaAB_2**2 &
        *sin( betaAB_2*theta)**2 + betaAB_1**2*cos(betaAB_2*theta)**2 + 2* betaAB_1*cos(betaAB_2 &
        *theta) + 1)
end subroutine nAB

! Subroutine uA
subroutine uA(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = -r*wA*sin(theta) + (-betaAB_1*betaAB_2*r**2*rAB*wA*sin(betaAB_2*theta) + betaAB_1*betaAB_2 &
        *r*rA*rAB*wA*sin(betaAB_2*theta))*cos(theta)/( betaAB_1*rAB*cos(betaAB_2*theta) - rA + rAB)
    res(2) = r*wA*cos(theta) + (-betaAB_1*betaAB_2*r**2*rAB*wA*sin(betaAB_2*theta) + betaAB_1*betaAB_2 &
        *r*rA*rAB*wA*sin(betaAB_2*theta))*sin(theta)/( betaAB_1*rAB*cos(betaAB_2*theta) - rA + rAB)
end subroutine uA

! Subroutine uB
subroutine uB(x, y, res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8), intent(out) :: res(2)
    real(8) :: r
    real(8) :: theta
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    res(1) = -r*wB*sin(theta) + (-betaAB_1*betaAB_2*r**2*rAB*wB*sin(betaAB_2*theta) + betaAB_1*betaAB_2 &
        *r*rAB*rB*wB*sin(betaAB_2*theta))*cos(theta)/( betaAB_1*rAB*cos(betaAB_2*theta) + rAB - rB)
    res(2) = r*wB*cos(theta) + (-betaAB_1*betaAB_2*r**2*rAB*wB*sin(betaAB_2*theta) + betaAB_1*betaAB_2 &
        *r*rAB*rB*wB*sin(betaAB_2*theta))*sin(theta)/( betaAB_1*rAB*cos(betaAB_2*theta) + rAB - rB)
end subroutine uB

! Function phiA
function phiA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log( rB) + alphaB*h*rAB &
        *log(rA) - alphaB*h*rAB*log(rAB))
    bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h *rAB*log(rAB)) &
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h* rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB &
        *h*rAB*log(rAB))
    res = aA*log((betaAB_1**2*r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB* cos(betaAB_2*theta) &
        + 2.0d0*betaAB_1*r*rAB**2*cos(betaAB_2*theta ) - betaAB_1*rA*rAB*rB*cos(betaAB_2 &
        *theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2 &
        *theta)**2 - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2.0d0*betaAB_1*rAB**2*cos( betaAB_2 &
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)) + bA
end function phiA

! Function phiB
function phiB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log( rB) + alphaB*h*rAB &
        *log(rA) - alphaB*h*rAB*log(rAB))
    bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h* rAB*log(rB) + alphaB &
        *h*rAB*log(rA) - alphaB*h*rAB*log(rAB))
    res = aB*log((betaAB_1**2*r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB* cos(betaAB_2*theta) &
        + 2.0d0*betaAB_1*r*rAB**2*cos(betaAB_2*theta ) - betaAB_1*rA*rAB*rB*cos(betaAB_2 &
        *theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2 &
        *theta)**2 - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2.0d0*betaAB_1*rAB**2*cos( betaAB_2 &
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)) + bB
end function phiB

! Function fA
function fA(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log( rB) + alphaB*h*rAB &
        *log(rA) - alphaB*h*rAB*log(rAB))
    bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h *rAB*log(rAB)) &
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h* rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB &
        *h*rAB*log(rAB))
    res = -alphaA*((-2*aA*betaAB_1*r*rAB*cos(betaAB_2*theta)/(betaAB_1**2*r*rAB**2 *cos(betaAB_2*theta) &
        **2 - betaAB_1*r**2*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rA*rAB*rB*cos( betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB) &
        + aA* r*(-betaAB_1**2*rAB**2*cos(betaAB_2*theta)**2 + 2*betaAB_1*r*rAB* cos(betaAB_2 &
        *theta) - 2*betaAB_1*rAB**2*cos(betaAB_2*theta) + rA* rAB - rA*rB - rAB**2 + rAB*rB) &
        *(betaAB_1**2*rAB**2*cos(betaAB_2* theta)**2 - 2*betaAB_1*r*rAB*cos(betaAB_2*theta) + 2 &
        *betaAB_1*rAB **2*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)/( betaAB_1**2 &
        *r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB* cos(betaAB_2*theta) + 2*betaAB_1 &
        *r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r &
        *rA*rB + r* rAB**2 - r*rAB*rB)**2 + aA*(betaAB_1**2*rAB**2*cos(betaAB_2*theta )**2 - 2 &
        *betaAB_1*r*rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2* cos(betaAB_2*theta) - rA*rAB &
        + rA*rB + rAB**2 - rAB*rB)/(betaAB_1 **2*r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r* &
        *2*rAB*cos( betaAB_2*theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB &
        *rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r* rAB**2 - r*rAB*rB))/r + (aA*((2 &
        *betaAB_1**2*betaAB_2*rAB**2*sin( betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*rA*rAB* sin(betaAB_2*theta) + 2*betaAB_1*betaAB_2*rAB**2*sin(betaAB_2 &
        * theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(betaAB_1 **2*r*rAB**2 &
        *cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB*cos( betaAB_2*theta) + 2*betaAB_1*r*rAB**2 &
        *cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r &
        * rAB**2 - r*rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*rA*rAB &
        *cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos( betaAB_2*theta) - betaAB_1*rAB*rB &
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 + (-2*betaAB_1**2*betaAB_2 &
        *r*rAB**2* sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2*r**2* rAB &
        *sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r*rAB**2*sin( betaAB_2*theta) + betaAB_1 &
        *betaAB_2*rA*rAB*rB*sin(betaAB_2*theta ))/(betaAB_1**2*rAB**2*cos(betaAB_2*theta)**2 &
        - betaAB_1*rA*rAB* cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB))*(-2*betaAB_1 &
        **2*betaAB_2*rAB**2*sin(betaAB_2*theta)*cos( betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB &
        *sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rAB**2*sin(betaAB_2*theta) + betaAB_1 &
        * betaAB_2*rAB*rB*sin(betaAB_2*theta))/(betaAB_1**2*r*rAB**2*cos( betaAB_2*theta)**2 &
        - betaAB_1*r**2*rAB*cos(betaAB_2*theta) + 2* betaAB_1*r*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rA*rAB*rB*cos( betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB) &
        + aA* ((2*betaAB_1**2*betaAB_2*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2* theta) &
        - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2* betaAB_1*betaAB_2*rAB**2 &
        *sin(betaAB_2*theta) - betaAB_1*betaAB_2* rAB*rB*sin(betaAB_2*theta))*(betaAB_1**2*r &
        *rAB**2*cos(betaAB_2* theta)**2 - betaAB_1*r**2*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r &
        * rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2* theta) - r*rA*rAB + r &
        *rA*rB + r*rAB**2 - r*rAB*rB)/(betaAB_1**2* rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*rA &
        *rAB*cos(betaAB_2* theta) + 2*betaAB_1*rAB**2*cos(betaAB_2*theta) - betaAB_1*rAB*rB &
        * cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 + (-2* betaAB_1**2 &
        *betaAB_2*r*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2* theta) + betaAB_1*betaAB_2*r**2 &
        *rAB*sin(betaAB_2*theta) - 2* betaAB_1*betaAB_2*r*rAB**2*sin(betaAB_2*theta) + betaAB_1 &
        * betaAB_2*rA*rAB*rB*sin(betaAB_2*theta))/(betaAB_1**2*rAB**2*cos( betaAB_2*theta)**2 &
        - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2* betaAB_1*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rAB*rB*cos( betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB))*(2 &
        *betaAB_1 **2*betaAB_2*r*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*r**2*rAB*sin(betaAB_2*theta) + 2*betaAB_1* betaAB_2*r*rAB**2*sin(betaAB_2 &
        *theta) - betaAB_1*betaAB_2*rA*rAB* rB*sin(betaAB_2*theta))*(betaAB_1**2*rAB**2 &
        *cos(betaAB_2*theta)** 2 - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2 &
        *cos( betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 &
        - rAB*rB)/(betaAB_1**2*r*rAB**2*cos(betaAB_2*theta )**2 - betaAB_1*r**2*rAB &
        *cos(betaAB_2*theta) + 2*betaAB_1*r*rAB** 2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB &
        *cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB)**2 + aA*((2*betaAB_1* &
        *2 *betaAB_2*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1*betaAB_2*rA*rAB &
        *sin(betaAB_2*theta) + 2*betaAB_1* betaAB_2*rAB**2*sin(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*rAB*rB* sin(betaAB_2*theta))*(4*betaAB_1**2*betaAB_2*rAB**2*sin(betaAB_2 &
        * theta)*cos(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rA*rAB*sin( betaAB_2*theta) + 4 &
        *betaAB_1*betaAB_2*rAB**2*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2 &
        *theta))*(betaAB_1**2*r* rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB*cos(betaAB_2 &
        * theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA* rAB*rB*cos(betaAB_2 &
        *theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r* rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2 &
        *theta)**2 - betaAB_1*rA* rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos(betaAB_2 &
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**3 &
        + 2*(2*betaAB_1**2*betaAB_2*rAB**2*sin(betaAB_2*theta) *cos(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*rA*rAB*sin(betaAB_2* theta) + 2*betaAB_1*betaAB_2*rAB**2*sin(betaAB_2*theta) &
        - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(-2*betaAB_1**2* betaAB_2*r*rAB**2 &
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2*r**2*rAB*sin(betaAB_2 &
        *theta) - 2*betaAB_1* betaAB_2*r*rAB**2*sin(betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB &
        * rB*sin(betaAB_2*theta))/(betaAB_1**2*rAB**2*cos(betaAB_2*theta)** 2 - betaAB_1*rA*rAB &
        *cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos( betaAB_2*theta) - betaAB_1*rAB*rB &
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 + (-2*betaAB_1**2*betaAB_2* &
        *2*rAB**2* sin(betaAB_2*theta)**2 + 2*betaAB_1**2*betaAB_2**2*rAB**2*cos( betaAB_2 &
        *theta)**2 - betaAB_1*betaAB_2**2*rA*rAB*cos(betaAB_2* theta) + 2*betaAB_1*betaAB_2**2 &
        *rAB**2*cos(betaAB_2*theta) - betaAB_1*betaAB_2**2*rAB*rB*cos(betaAB_2*theta)) &
        *(betaAB_1**2*r* rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB*cos(betaAB_2 &
        * theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA* rAB*rB*cos(betaAB_2 &
        *theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r* rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2 &
        *theta)**2 - betaAB_1*rA* rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos(betaAB_2 &
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 &
        + (2*betaAB_1**2*betaAB_2**2*r*rAB**2*sin(betaAB_2* theta)**2 - 2*betaAB_1**2*betaAB_2* &
        *2*r*rAB**2*cos(betaAB_2*theta )**2 + betaAB_1*betaAB_2**2*r**2*rAB*cos(betaAB_2 &
        *theta) - 2* betaAB_1*betaAB_2**2*r*rAB**2*cos(betaAB_2*theta) + betaAB_1* betaAB_2**2 &
        *rA*rAB*rB*cos(betaAB_2*theta))/(betaAB_1**2*rAB**2* cos(betaAB_2*theta)**2 - betaAB_1 &
        *rA*rAB*cos(betaAB_2*theta) + 2* betaAB_1*rAB**2*cos(betaAB_2*theta) - betaAB_1*rAB*rB &
        *cos( betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB))*(betaAB_1**2 *rAB**2 &
        *cos(betaAB_2*theta)**2 - betaAB_1*rA*rAB*cos(betaAB_2* theta) + 2*betaAB_1*rAB**2 &
        *cos(betaAB_2*theta) - betaAB_1*rAB*rB* cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 &
        - rAB*rB)/(betaAB_1 **2*r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB &
        *cos( betaAB_2*theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB &
        *cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r* rAB**2 - r*rAB*rB))/r**2) + (aA*betaAB_1 &
        **4*betaAB_2*r**2*rAB**4* wA*sin(betaAB_2*theta)*cos(betaAB_2*theta)**3 - aA*betaAB_1* &
        *4* betaAB_2*r*rA*rAB**4*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta)** 3 - 2*aA*betaAB_1 &
        **3*betaAB_2*r**3*rAB**3*wA*sin(betaAB_2*theta)* cos(betaAB_2*theta)**2 + 2*aA*betaAB_1 &
        **3*betaAB_2*r**2*rA*rAB**3 *wA*sin(betaAB_2*theta)*cos(betaAB_2*theta)**2 + 3*aA &
        *betaAB_1**3 *betaAB_2*r**2*rAB**4*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta) **2 - aA &
        *betaAB_1**3*betaAB_2*r**2*rAB**3*rB*wA*sin(betaAB_2* theta)*cos(betaAB_2*theta)**2 &
        + aA*betaAB_1**3*betaAB_2*r**2*rAB **3*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta)**2 &
        - 3*aA*betaAB_1 **3*betaAB_2*r*rA*rAB**4*wA*sin(betaAB_2*theta)*cos(betaAB_2* theta)* &
        *2 + aA*betaAB_1**3*betaAB_2*r*rA*rAB**3*rB*wA*sin( betaAB_2*theta)*cos(betaAB_2*theta) &
        **2 - aA*betaAB_1**3*betaAB_2* r*rA*rAB**3*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta)* &
        *2 - aA* betaAB_1**3*betaAB_2*r*rAB**3*rB*wA*sin(betaAB_2*theta)*cos( betaAB_2*theta)* &
        *2 + aA*betaAB_1**3*betaAB_2*rA*rAB**3*rB*wA*sin( betaAB_2*theta)*cos(betaAB_2*theta)* &
        *2 - 2*aA*betaAB_1**2* betaAB_2*r**3*rAB**3*wA*sin(betaAB_2*theta)*cos(betaAB_2*theta) &
        + 2*aA*betaAB_1**2*betaAB_2*r**3*rAB**2*rB*wA*sin(betaAB_2*theta)* cos(betaAB_2*theta) &
        + aA*betaAB_1**2*betaAB_2*r**2*rA*rAB**3*wA* sin(betaAB_2*theta)*cos(betaAB_2*theta) &
        - aA*betaAB_1**2*betaAB_2 *r**2*rA*rAB**2*rB*wA*sin(betaAB_2*theta)*cos(betaAB_2 &
        *theta) + 3 *aA*betaAB_1**2*betaAB_2*r**2*rAB**4*wA*sin(betaAB_2*theta)*cos( betaAB_2 &
        *theta) - 3*aA*betaAB_1**2*betaAB_2*r**2*rAB**3*rB*wA*sin (betaAB_2*theta)*cos(betaAB_2 &
        *theta) + aA*betaAB_1**2*betaAB_2*r* rA**2*rAB**3*wA*sin(betaAB_2*theta)*cos(betaAB_2 &
        *theta) - aA* betaAB_1**2*betaAB_2*r*rA**2*rAB**2*rB*wA*sin(betaAB_2*theta) &
        *cos (betaAB_2*theta) - 3*aA*betaAB_1**2*betaAB_2*r*rA*rAB**4*wA*sin( betaAB_2*theta) &
        *cos(betaAB_2*theta) + 3*aA*betaAB_1**2*betaAB_2*r *rA*rAB**3*rB*wA*sin(betaAB_2*theta) &
        *cos(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r**2*rA*rAB**3*wA*sin(betaAB_2*theta) + 2 &
        *aA* betaAB_1*betaAB_2*r**2*rA*rAB**2*rB*wA*sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2 &
        *r**2*rA*rAB**2*wA*sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r**2*rA*rAB*rB**2*wA &
        *sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r**2*rA*rAB*rB*wA*sin(betaAB_2*theta) + aA &
        * betaAB_1*betaAB_2*r**2*rAB**4*wA*sin(betaAB_2*theta) - 2*aA* betaAB_1*betaAB_2*r**2 &
        *rAB**3*rB*wA*sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r**2*rAB**3*wA*sin(betaAB_2 &
        *theta) + aA* betaAB_1*betaAB_2*r**2*rAB**2*rB**2*wA*sin(betaAB_2*theta) + aA* betaAB_1 &
        *betaAB_2*r**2*rAB**2*rB*wA*sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2*r*rA**2*rAB**3 &
        *wA*sin(betaAB_2*theta) - 2*aA* betaAB_1*betaAB_2*r*rA**2*rAB**2*rB*wA*sin(betaAB_2 &
        *theta) - aA* betaAB_1*betaAB_2*r*rA**2*rAB**2*wA*sin(betaAB_2*theta) + aA* betaAB_1 &
        *betaAB_2*r*rA**2*rAB*rB**2*wA*sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2*r*rA**2*rAB &
        *rB*wA*sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r*rA*rAB**4*wA*sin(betaAB_2*theta) &
        + 2*aA* betaAB_1*betaAB_2*r*rA*rAB**3*rB*wA*sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2 &
        *r*rA*rAB**3*wA*sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r*rA*rAB**2*rB**2*wA &
        *sin(betaAB_2*theta) - 2*aA *betaAB_1*betaAB_2*r*rA*rAB**2*rB*wA*sin(betaAB_2*theta) &
        + aA* betaAB_1*betaAB_2*r*rA*rAB*rB**2*wA*sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2*r &
        *rAB**3*rB*wA*sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2*r*rAB**2*rB**2*wA &
        *sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2*rA**2*rAB**2*rB*wA*sin(betaAB_2*theta) &
        - aA* betaAB_1*betaAB_2*rA**2*rAB*rB**2*wA*sin(betaAB_2*theta) - aA* betaAB_1*betaAB_2 &
        *rA*rAB**3*rB*wA*sin(betaAB_2*theta) + aA* betaAB_1*betaAB_2*rA*rAB**2*rB**2*wA &
        *sin(betaAB_2*theta))/( -betaAB_1**4*r*rAB**4*cos(betaAB_2*theta)**4 + betaAB_1**3*r**2 &
        * rAB**3*cos(betaAB_2*theta)**3 + betaAB_1**3*r*rA*rAB**3*cos( betaAB_2*theta)**3 - 4 &
        *betaAB_1**3*r*rAB**4*cos(betaAB_2*theta)** 3 + betaAB_1**3*r*rAB**3*rB*cos(betaAB_2 &
        *theta)**3 + betaAB_1**3* rA*rAB**3*rB*cos(betaAB_2*theta)**3 - betaAB_1**2*r**2*rA*rAB &
        **2* cos(betaAB_2*theta)**2 + 2*betaAB_1**2*r**2*rAB**3*cos(betaAB_2* theta)**2 &
        - betaAB_1**2*r**2*rAB**2*rB*cos(betaAB_2*theta)**2 + 4 *betaAB_1**2*r*rA*rAB**3 &
        *cos(betaAB_2*theta)**2 - 2*betaAB_1**2*r *rA*rAB**2*rB*cos(betaAB_2*theta)**2 - 6 &
        *betaAB_1**2*r*rAB**4*cos (betaAB_2*theta)**2 + 4*betaAB_1**2*r*rAB**3*rB*cos(betaAB_2 &
        * theta)**2 - betaAB_1**2*rA**2*rAB**2*rB*cos(betaAB_2*theta)**2 + 2*betaAB_1**2*rA*rAB &
        **3*rB*cos(betaAB_2*theta)**2 - betaAB_1**2* rA*rAB**2*rB**2*cos(betaAB_2*theta)**2 &
        - betaAB_1*r**2*rA*rAB**2* cos(betaAB_2*theta) + betaAB_1*r**2*rA*rAB*rB*cos(betaAB_2 &
        *theta ) + betaAB_1*r**2*rAB**3*cos(betaAB_2*theta) - betaAB_1*r**2*rAB **2*rB &
        *cos(betaAB_2*theta) - betaAB_1*r*rA**2*rAB**2*cos(betaAB_2 *theta) + betaAB_1*r*rA**2 &
        *rAB*rB*cos(betaAB_2*theta) + 5* betaAB_1*r*rA*rAB**3*cos(betaAB_2*theta) - 6*betaAB_1 &
        *r*rA*rAB**2 *rB*cos(betaAB_2*theta) + betaAB_1*r*rA*rAB*rB**2*cos(betaAB_2* theta) - 4 &
        *betaAB_1*r*rAB**4*cos(betaAB_2*theta) + 5*betaAB_1*r* rAB**3*rB*cos(betaAB_2*theta) &
        - betaAB_1*r*rAB**2*rB**2*cos( betaAB_2*theta) - betaAB_1*rA**2*rAB**2*rB*cos(betaAB_2 &
        *theta) + betaAB_1*rA**2*rAB*rB**2*cos(betaAB_2*theta) + betaAB_1*rA*rAB**3 *rB &
        *cos(betaAB_2*theta) - betaAB_1*rA*rAB**2*rB**2*cos(betaAB_2* theta) - r*rA**2*rAB**2 &
        + 2*r*rA**2*rAB*rB - r*rA**2*rB**2 + 2*r* rA*rAB**3 - 4*r*rA*rAB**2*rB + 2*r*rA*rAB*rB* &
        *2 - r*rAB**4 + 2*r* rAB**3*rB - r*rAB**2*rB**2)
end function fA

! Function fB
function fB(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log( rB) + alphaB*h*rAB &
        *log(rA) - alphaB*h*rAB*log(rAB))
    bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h* rAB*log(rB) + alphaB &
        *h*rAB*log(rA) - alphaB*h*rAB*log(rAB))
    res = -alphaB*((-2*aB*betaAB_1*r*rAB*cos(betaAB_2*theta)/(betaAB_1**2*r*rAB**2 *cos(betaAB_2*theta) &
        **2 - betaAB_1*r**2*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rA*rAB*rB*cos( betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB) &
        + aB* r*(-betaAB_1**2*rAB**2*cos(betaAB_2*theta)**2 + 2*betaAB_1*r*rAB* cos(betaAB_2 &
        *theta) - 2*betaAB_1*rAB**2*cos(betaAB_2*theta) + rA* rAB - rA*rB - rAB**2 + rAB*rB) &
        *(betaAB_1**2*rAB**2*cos(betaAB_2* theta)**2 - 2*betaAB_1*r*rAB*cos(betaAB_2*theta) + 2 &
        *betaAB_1*rAB **2*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)/( betaAB_1**2 &
        *r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB* cos(betaAB_2*theta) + 2*betaAB_1 &
        *r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r &
        *rA*rB + r* rAB**2 - r*rAB*rB)**2 + aB*(betaAB_1**2*rAB**2*cos(betaAB_2*theta )**2 - 2 &
        *betaAB_1*r*rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2* cos(betaAB_2*theta) - rA*rAB &
        + rA*rB + rAB**2 - rAB*rB)/(betaAB_1 **2*r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r* &
        *2*rAB*cos( betaAB_2*theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB &
        *rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r* rAB**2 - r*rAB*rB))/r + (aB*((2 &
        *betaAB_1**2*betaAB_2*rAB**2*sin( betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*rA*rAB* sin(betaAB_2*theta) + 2*betaAB_1*betaAB_2*rAB**2*sin(betaAB_2 &
        * theta) - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(betaAB_1 **2*r*rAB**2 &
        *cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB*cos( betaAB_2*theta) + 2*betaAB_1*r*rAB**2 &
        *cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r &
        * rAB**2 - r*rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*rA*rAB &
        *cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos( betaAB_2*theta) - betaAB_1*rAB*rB &
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 + (-2*betaAB_1**2*betaAB_2 &
        *r*rAB**2* sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2*r**2* rAB &
        *sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*r*rAB**2*sin( betaAB_2*theta) + betaAB_1 &
        *betaAB_2*rA*rAB*rB*sin(betaAB_2*theta ))/(betaAB_1**2*rAB**2*cos(betaAB_2*theta)**2 &
        - betaAB_1*rA*rAB* cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB))*(-2*betaAB_1 &
        **2*betaAB_2*rAB**2*sin(betaAB_2*theta)*cos( betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB &
        *sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rAB**2*sin(betaAB_2*theta) + betaAB_1 &
        * betaAB_2*rAB*rB*sin(betaAB_2*theta))/(betaAB_1**2*r*rAB**2*cos( betaAB_2*theta)**2 &
        - betaAB_1*r**2*rAB*cos(betaAB_2*theta) + 2* betaAB_1*r*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rA*rAB*rB*cos( betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB) &
        + aB* ((2*betaAB_1**2*betaAB_2*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2* theta) &
        - betaAB_1*betaAB_2*rA*rAB*sin(betaAB_2*theta) + 2* betaAB_1*betaAB_2*rAB**2 &
        *sin(betaAB_2*theta) - betaAB_1*betaAB_2* rAB*rB*sin(betaAB_2*theta))*(betaAB_1**2*r &
        *rAB**2*cos(betaAB_2* theta)**2 - betaAB_1*r**2*rAB*cos(betaAB_2*theta) + 2*betaAB_1*r &
        * rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB*cos(betaAB_2* theta) - r*rA*rAB + r &
        *rA*rB + r*rAB**2 - r*rAB*rB)/(betaAB_1**2* rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*rA &
        *rAB*cos(betaAB_2* theta) + 2*betaAB_1*rAB**2*cos(betaAB_2*theta) - betaAB_1*rAB*rB &
        * cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 + (-2* betaAB_1**2 &
        *betaAB_2*r*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2* theta) + betaAB_1*betaAB_2*r**2 &
        *rAB*sin(betaAB_2*theta) - 2* betaAB_1*betaAB_2*r*rAB**2*sin(betaAB_2*theta) + betaAB_1 &
        * betaAB_2*rA*rAB*rB*sin(betaAB_2*theta))/(betaAB_1**2*rAB**2*cos( betaAB_2*theta)**2 &
        - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2* betaAB_1*rAB**2*cos(betaAB_2*theta) &
        - betaAB_1*rAB*rB*cos( betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB))*(2 &
        *betaAB_1 **2*betaAB_2*r*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*r**2*rAB*sin(betaAB_2*theta) + 2*betaAB_1* betaAB_2*r*rAB**2*sin(betaAB_2 &
        *theta) - betaAB_1*betaAB_2*rA*rAB* rB*sin(betaAB_2*theta))*(betaAB_1**2*rAB**2 &
        *cos(betaAB_2*theta)** 2 - betaAB_1*rA*rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2 &
        *cos( betaAB_2*theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 &
        - rAB*rB)/(betaAB_1**2*r*rAB**2*cos(betaAB_2*theta )**2 - betaAB_1*r**2*rAB &
        *cos(betaAB_2*theta) + 2*betaAB_1*r*rAB** 2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB &
        *cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r*rAB*rB)**2 + aB*((2*betaAB_1* &
        *2 *betaAB_2*rAB**2*sin(betaAB_2*theta)*cos(betaAB_2*theta) - betaAB_1*betaAB_2*rA*rAB &
        *sin(betaAB_2*theta) + 2*betaAB_1* betaAB_2*rAB**2*sin(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*rAB*rB* sin(betaAB_2*theta))*(4*betaAB_1**2*betaAB_2*rAB**2*sin(betaAB_2 &
        * theta)*cos(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rA*rAB*sin( betaAB_2*theta) + 4 &
        *betaAB_1*betaAB_2*rAB**2*sin(betaAB_2*theta) - 2*betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2 &
        *theta))*(betaAB_1**2*r* rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB*cos(betaAB_2 &
        * theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA* rAB*rB*cos(betaAB_2 &
        *theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r* rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2 &
        *theta)**2 - betaAB_1*rA* rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos(betaAB_2 &
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**3 &
        + 2*(2*betaAB_1**2*betaAB_2*rAB**2*sin(betaAB_2*theta) *cos(betaAB_2*theta) - betaAB_1 &
        *betaAB_2*rA*rAB*sin(betaAB_2* theta) + 2*betaAB_1*betaAB_2*rAB**2*sin(betaAB_2*theta) &
        - betaAB_1*betaAB_2*rAB*rB*sin(betaAB_2*theta))*(-2*betaAB_1**2* betaAB_2*r*rAB**2 &
        *sin(betaAB_2*theta)*cos(betaAB_2*theta) + betaAB_1*betaAB_2*r**2*rAB*sin(betaAB_2 &
        *theta) - 2*betaAB_1* betaAB_2*r*rAB**2*sin(betaAB_2*theta) + betaAB_1*betaAB_2*rA*rAB &
        * rB*sin(betaAB_2*theta))/(betaAB_1**2*rAB**2*cos(betaAB_2*theta)** 2 - betaAB_1*rA*rAB &
        *cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos( betaAB_2*theta) - betaAB_1*rAB*rB &
        *cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 + (-2*betaAB_1**2*betaAB_2* &
        *2*rAB**2* sin(betaAB_2*theta)**2 + 2*betaAB_1**2*betaAB_2**2*rAB**2*cos( betaAB_2 &
        *theta)**2 - betaAB_1*betaAB_2**2*rA*rAB*cos(betaAB_2* theta) + 2*betaAB_1*betaAB_2**2 &
        *rAB**2*cos(betaAB_2*theta) - betaAB_1*betaAB_2**2*rAB*rB*cos(betaAB_2*theta)) &
        *(betaAB_1**2*r* rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB*cos(betaAB_2 &
        * theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA* rAB*rB*cos(betaAB_2 &
        *theta) - r*rA*rAB + r*rA*rB + r*rAB**2 - r* rAB*rB)/(betaAB_1**2*rAB**2*cos(betaAB_2 &
        *theta)**2 - betaAB_1*rA* rAB*cos(betaAB_2*theta) + 2*betaAB_1*rAB**2*cos(betaAB_2 &
        *theta) - betaAB_1*rAB*rB*cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB)**2 &
        + (2*betaAB_1**2*betaAB_2**2*r*rAB**2*sin(betaAB_2* theta)**2 - 2*betaAB_1**2*betaAB_2* &
        *2*r*rAB**2*cos(betaAB_2*theta )**2 + betaAB_1*betaAB_2**2*r**2*rAB*cos(betaAB_2 &
        *theta) - 2* betaAB_1*betaAB_2**2*r*rAB**2*cos(betaAB_2*theta) + betaAB_1* betaAB_2**2 &
        *rA*rAB*rB*cos(betaAB_2*theta))/(betaAB_1**2*rAB**2* cos(betaAB_2*theta)**2 - betaAB_1 &
        *rA*rAB*cos(betaAB_2*theta) + 2* betaAB_1*rAB**2*cos(betaAB_2*theta) - betaAB_1*rAB*rB &
        *cos( betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 - rAB*rB))*(betaAB_1**2 *rAB**2 &
        *cos(betaAB_2*theta)**2 - betaAB_1*rA*rAB*cos(betaAB_2* theta) + 2*betaAB_1*rAB**2 &
        *cos(betaAB_2*theta) - betaAB_1*rAB*rB* cos(betaAB_2*theta) - rA*rAB + rA*rB + rAB**2 &
        - rAB*rB)/(betaAB_1 **2*r*rAB**2*cos(betaAB_2*theta)**2 - betaAB_1*r**2*rAB &
        *cos( betaAB_2*theta) + 2*betaAB_1*r*rAB**2*cos(betaAB_2*theta) - betaAB_1*rA*rAB*rB &
        *cos(betaAB_2*theta) - r*rA*rAB + r*rA*rB + r* rAB**2 - r*rAB*rB))/r**2) + (aB*betaAB_1 &
        **4*betaAB_2*r**2*rAB**4* wB*sin(betaAB_2*theta)*cos(betaAB_2*theta)**3 - aB*betaAB_1* &
        *4* betaAB_2*r*rAB**4*rB*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta)** 3 - 2*aB*betaAB_1 &
        **3*betaAB_2*r**3*rAB**3*wB*sin(betaAB_2*theta)* cos(betaAB_2*theta)**2 - aB*betaAB_1* &
        *3*betaAB_2*r**2*rA*rAB**3* wB*sin(betaAB_2*theta)*cos(betaAB_2*theta)**2 + 3*aB &
        *betaAB_1**3* betaAB_2*r**2*rAB**4*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta)** 2 + 2 &
        *aB*betaAB_1**3*betaAB_2*r**2*rAB**3*rB*wB*sin(betaAB_2* theta)*cos(betaAB_2*theta)**2 &
        + aB*betaAB_1**3*betaAB_2*r**2*rAB **3*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta)**2 &
        + aB*betaAB_1** 3*betaAB_2*r*rA*rAB**3*rB*wB*sin(betaAB_2*theta)*cos(betaAB_2* theta)* &
        *2 - aB*betaAB_1**3*betaAB_2*r*rA*rAB**3*wB*sin(betaAB_2* theta)*cos(betaAB_2*theta)* &
        *2 - 3*aB*betaAB_1**3*betaAB_2*r*rAB** 4*rB*wB*sin(betaAB_2*theta)*cos(betaAB_2*theta)* &
        *2 - aB*betaAB_1 **3*betaAB_2*r*rAB**3*rB*wB*sin(betaAB_2*theta)*cos(betaAB_2* theta)* &
        *2 + aB*betaAB_1**3*betaAB_2*rA*rAB**3*rB*wB*sin(betaAB_2* theta)*cos(betaAB_2*theta)* &
        *2 + 2*aB*betaAB_1**2*betaAB_2*r**3*rA *rAB**2*wB*sin(betaAB_2*theta)*cos(betaAB_2 &
        *theta) - 2*aB* betaAB_1**2*betaAB_2*r**3*rAB**3*wB*sin(betaAB_2*theta)*cos( betaAB_2 &
        *theta) - 3*aB*betaAB_1**2*betaAB_2*r**2*rA*rAB**3*wB*sin (betaAB_2*theta)*cos(betaAB_2 &
        *theta) - aB*betaAB_1**2*betaAB_2*r **2*rA*rAB**2*rB*wB*sin(betaAB_2*theta) &
        *cos(betaAB_2*theta) + 3* aB*betaAB_1**2*betaAB_2*r**2*rAB**4*wB*sin(betaAB_2*theta) &
        *cos( betaAB_2*theta) + aB*betaAB_1**2*betaAB_2*r**2*rAB**3*rB*wB*sin( betaAB_2*theta) &
        *cos(betaAB_2*theta) + 3*aB*betaAB_1**2*betaAB_2*r *rA*rAB**3*rB*wB*sin(betaAB_2*theta) &
        *cos(betaAB_2*theta) - aB* betaAB_1**2*betaAB_2*r*rA*rAB**2*rB**2*wB*sin(betaAB_2 &
        *theta)*cos (betaAB_2*theta) - 3*aB*betaAB_1**2*betaAB_2*r*rAB**4*rB*wB*sin( betaAB_2 &
        *theta)*cos(betaAB_2*theta) + aB*betaAB_1**2*betaAB_2*r* rAB**3*rB**2*wB*sin(betaAB_2 &
        *theta)*cos(betaAB_2*theta) + aB* betaAB_1*betaAB_2*r**2*rA**2*rAB**2*wB*sin(betaAB_2 &
        *theta) - aB* betaAB_1*betaAB_2*r**2*rA**2*rAB*rB*wB*sin(betaAB_2*theta) - 2*aB &
        *betaAB_1*betaAB_2*r**2*rA*rAB**3*wB*sin(betaAB_2*theta) + 2*aB* betaAB_1*betaAB_2*r**2 &
        *rA*rAB**2*rB*wB*sin(betaAB_2*theta) + aB* betaAB_1*betaAB_2*r**2*rA*rAB**2*wB &
        *sin(betaAB_2*theta) - aB* betaAB_1*betaAB_2*r**2*rA*rAB*rB*wB*sin(betaAB_2*theta) + aB &
        * betaAB_1*betaAB_2*r**2*rAB**4*wB*sin(betaAB_2*theta) - aB* betaAB_1*betaAB_2*r**2*rAB &
        **3*rB*wB*sin(betaAB_2*theta) - aB* betaAB_1*betaAB_2*r**2*rAB**3*wB*sin(betaAB_2 &
        *theta) + aB* betaAB_1*betaAB_2*r**2*rAB**2*rB*wB*sin(betaAB_2*theta) - aB* betaAB_1 &
        *betaAB_2*r*rA**2*rAB**2*rB*wB*sin(betaAB_2*theta) - aB* betaAB_1*betaAB_2*r*rA**2*rAB* &
        *2*wB*sin(betaAB_2*theta) + aB* betaAB_1*betaAB_2*r*rA**2*rAB*rB**2*wB*sin(betaAB_2 &
        *theta) + aB* betaAB_1*betaAB_2*r*rA**2*rAB*rB*wB*sin(betaAB_2*theta) + 2*aB* betaAB_1 &
        *betaAB_2*r*rA*rAB**3*rB*wB*sin(betaAB_2*theta) + aB* betaAB_1*betaAB_2*r*rA*rAB**3*wB &
        *sin(betaAB_2*theta) - 2*aB* betaAB_1*betaAB_2*r*rA*rAB**2*rB**2*wB*sin(betaAB_2 &
        *theta) - 2*aB *betaAB_1*betaAB_2*r*rA*rAB**2*rB*wB*sin(betaAB_2*theta) + aB* betaAB_1 &
        *betaAB_2*r*rA*rAB*rB**2*wB*sin(betaAB_2*theta) - aB* betaAB_1*betaAB_2*r*rAB**4*rB*wB &
        *sin(betaAB_2*theta) + aB* betaAB_1*betaAB_2*r*rAB**3*rB**2*wB*sin(betaAB_2*theta) + aB &
        * betaAB_1*betaAB_2*r*rAB**3*rB*wB*sin(betaAB_2*theta) - aB* betaAB_1*betaAB_2*r*rAB**2 &
        *rB**2*wB*sin(betaAB_2*theta) + aB* betaAB_1*betaAB_2*rA**2*rAB**2*rB*wB*sin(betaAB_2 &
        *theta) - aB* betaAB_1*betaAB_2*rA**2*rAB*rB**2*wB*sin(betaAB_2*theta) - aB* betaAB_1 &
        *betaAB_2*rA*rAB**3*rB*wB*sin(betaAB_2*theta) + aB* betaAB_1*betaAB_2*rA*rAB**2*rB**2 &
        *wB*sin(betaAB_2*theta))/( -betaAB_1**4*r*rAB**4*cos(betaAB_2*theta)**4 + betaAB_1**3*r &
        **2* rAB**3*cos(betaAB_2*theta)**3 + betaAB_1**3*r*rA*rAB**3*cos( betaAB_2*theta)**3 &
        - 4*betaAB_1**3*r*rAB**4*cos(betaAB_2*theta)** 3 + betaAB_1**3*r*rAB**3*rB*cos(betaAB_2 &
        *theta)**3 + betaAB_1**3* rA*rAB**3*rB*cos(betaAB_2*theta)**3 - betaAB_1**2*r**2*rA*rAB &
        **2* cos(betaAB_2*theta)**2 + 2*betaAB_1**2*r**2*rAB**3*cos(betaAB_2* theta)**2 &
        - betaAB_1**2*r**2*rAB**2*rB*cos(betaAB_2*theta)**2 + 4 *betaAB_1**2*r*rA*rAB**3 &
        *cos(betaAB_2*theta)**2 - 2*betaAB_1**2*r *rA*rAB**2*rB*cos(betaAB_2*theta)**2 - 6 &
        *betaAB_1**2*r*rAB**4*cos (betaAB_2*theta)**2 + 4*betaAB_1**2*r*rAB**3*rB*cos(betaAB_2 &
        * theta)**2 - betaAB_1**2*rA**2*rAB**2*rB*cos(betaAB_2*theta)**2 + 2*betaAB_1**2*rA*rAB &
        **3*rB*cos(betaAB_2*theta)**2 - betaAB_1**2* rA*rAB**2*rB**2*cos(betaAB_2*theta)**2 &
        - betaAB_1*r**2*rA*rAB**2* cos(betaAB_2*theta) + betaAB_1*r**2*rA*rAB*rB*cos(betaAB_2 &
        *theta ) + betaAB_1*r**2*rAB**3*cos(betaAB_2*theta) - betaAB_1*r**2*rAB **2*rB &
        *cos(betaAB_2*theta) - betaAB_1*r*rA**2*rAB**2*cos(betaAB_2 *theta) + betaAB_1*r*rA**2 &
        *rAB*rB*cos(betaAB_2*theta) + 5* betaAB_1*r*rA*rAB**3*cos(betaAB_2*theta) - 6*betaAB_1 &
        *r*rA*rAB**2 *rB*cos(betaAB_2*theta) + betaAB_1*r*rA*rAB*rB**2*cos(betaAB_2* theta) - 4 &
        *betaAB_1*r*rAB**4*cos(betaAB_2*theta) + 5*betaAB_1*r* rAB**3*rB*cos(betaAB_2*theta) &
        - betaAB_1*r*rAB**2*rB**2*cos( betaAB_2*theta) - betaAB_1*rA**2*rAB**2*rB*cos(betaAB_2 &
        *theta) + betaAB_1*rA**2*rAB*rB**2*cos(betaAB_2*theta) + betaAB_1*rA*rAB**3 *rB &
        *cos(betaAB_2*theta) - betaAB_1*rA*rAB**2*rB**2*cos(betaAB_2* theta) - r*rA**2*rAB**2 &
        + 2*r*rA**2*rAB*rB - r*rA**2*rB**2 + 2*r* rA*rAB**3 - 4*r*rA*rAB**2*rB + 2*r*rA*rAB*rB* &
        *2 - r*rAB**4 + 2*r* rAB**3*rB - r*rAB**2*rB**2)
end function fB

! Function H
function H(x, y) result(res)
    real(8), intent(in) :: x
    real(8), intent(in) :: y
    real(8) :: res
    real(8) :: r
    real(8) :: theta
    real(8) :: aA
    real(8) :: bA
    real(8) :: aB
    real(8) :: bB
    r = sqrt(x**2 + y**2)
    theta = atan2(y, x)
    aA = alphaB*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log( rB) + alphaB*h*rAB &
        *log(rA) - alphaB*h*rAB*log(rAB))
    bA = (alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log(rB) - alphaB*h *rAB*log(rAB)) &
        /(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h* rAB*log(rB) + alphaB*h*rAB*log(rA) - alphaB &
        *h*rAB*log(rAB))
    aB = alphaA*h*rAB/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h*rAB*log( rB) + alphaB*h*rAB &
        *log(rA) - alphaB*h*rAB*log(rAB))
    bB = -alphaA*h*rAB*log(rB)/(alphaA*alphaB + alphaA*h*rAB*log(rAB) - alphaA*h* rAB*log(rB) + alphaB &
        *h*rAB*log(rA) - alphaB*h*rAB*log(rAB))
    res = (aA*alphaA*betaAB_1**2*rAB**2*sqrt(betaAB_1**2*betaAB_2**2*sin(betaAB_2* theta)**2 + betaAB_1 &
        **2*cos(betaAB_2*theta)**2 + 2*betaAB_1*cos( betaAB_2*theta) + 1)*cos(betaAB_2*theta)* &
        *2 + aA*alphaA*rA*rAB* sqrt(betaAB_1**2*betaAB_2**2*sin(betaAB_2*theta)**2 + betaAB_1* &
        *2 *cos(betaAB_2*theta)**2 + 2*betaAB_1*cos(betaAB_2*theta) + 1) - aA*alphaA*rA*rB &
        *sqrt(betaAB_1**2*betaAB_2**2*sin(betaAB_2*theta) **2 + betaAB_1**2*cos(betaAB_2*theta) &
        **2 + 2*betaAB_1*cos( betaAB_2*theta) + 1) - aA*alphaA*rAB**2*sqrt(betaAB_1**2 &
        *betaAB_2 **2*sin(betaAB_2*theta)**2 + betaAB_1**2*cos(betaAB_2*theta)**2 + 2*betaAB_1 &
        *cos(betaAB_2*theta) + 1) + aA*alphaA*rAB*rB*sqrt( betaAB_1**2*betaAB_2**2*sin(betaAB_2 &
        *theta)**2 + betaAB_1**2*cos( betaAB_2*theta)**2 + 2*betaAB_1*cos(betaAB_2*theta) + 1)) &
        /(aA* betaAB_1**3*rAB**3*log(rAB)*cos(betaAB_2*theta)**3 - aA*betaAB_1 **2*rA*rAB**2 &
        *log(rAB)*cos(betaAB_2*theta)**2 + 3*aA*betaAB_1**2* rAB**3*log(rAB)*cos(betaAB_2 &
        *theta)**2 - aA*betaAB_1**2*rAB**2*rB *log(rAB)*cos(betaAB_2*theta)**2 - 2*aA*betaAB_1 &
        *rA*rAB**2*log( rAB)*cos(betaAB_2*theta) + aA*betaAB_1*rA*rAB*rB*log(rAB)*cos( betaAB_2 &
        *theta) + 3*aA*betaAB_1*rAB**3*log(rAB)*cos(betaAB_2* theta) - 2*aA*betaAB_1*rAB**2*rB &
        *log(rAB)*cos(betaAB_2*theta) - aA*rA*rAB**2*log(rAB) + aA*rA*rAB*rB*log(rAB) + aA*rAB* &
        *3*log(rAB ) - aA*rAB**2*rB*log(rAB) - aB*betaAB_1**3*rAB**3*log(rAB)*cos( betaAB_2 &
        *theta)**3 + aB*betaAB_1**2*rA*rAB**2*log(rAB)*cos( betaAB_2*theta)**2 - 3*aB*betaAB_1* &
        *2*rAB**3*log(rAB)*cos( betaAB_2*theta)**2 + aB*betaAB_1**2*rAB**2*rB*log(rAB) &
        *cos( betaAB_2*theta)**2 + 2*aB*betaAB_1*rA*rAB**2*log(rAB)*cos( betaAB_2*theta) - aB &
        *betaAB_1*rA*rAB*rB*log(rAB)*cos(betaAB_2* theta) - 3*aB*betaAB_1*rAB**3*log(rAB) &
        *cos(betaAB_2*theta) + 2*aB *betaAB_1*rAB**2*rB*log(rAB)*cos(betaAB_2*theta) + aB*rA &
        *rAB**2* log(rAB) - aB*rA*rAB*rB*log(rAB) - aB*rAB**3*log(rAB) + aB*rAB**2 *rB &
        *log(rAB) + bA*betaAB_1**3*rAB**3*cos(betaAB_2*theta)**3 - bA* betaAB_1**2*rA*rAB**2 &
        *cos(betaAB_2*theta)**2 + 3*bA*betaAB_1**2* rAB**3*cos(betaAB_2*theta)**2 - bA*betaAB_1 &
        **2*rAB**2*rB*cos( betaAB_2*theta)**2 - 2*bA*betaAB_1*rA*rAB**2*cos(betaAB_2*theta) &
        + bA*betaAB_1*rA*rAB*rB*cos(betaAB_2*theta) + 3*bA*betaAB_1*rAB** 3*cos(betaAB_2 &
        *theta) - 2*bA*betaAB_1*rAB**2*rB*cos(betaAB_2* theta) - bA*rA*rAB**2 + bA*rA*rAB*rB &
        + bA*rAB**3 - bA*rAB**2*rB - bB*betaAB_1**3*rAB**3*cos(betaAB_2*theta)**3 + bB*betaAB_1 &
        **2*rA* rAB**2*cos(betaAB_2*theta)**2 - 3*bB*betaAB_1**2*rAB**3*cos( betaAB_2*theta)* &
        *2 + bB*betaAB_1**2*rAB**2*rB*cos(betaAB_2*theta) **2 + 2*bB*betaAB_1*rA*rAB**2 &
        *cos(betaAB_2*theta) - bB*betaAB_1* rA*rAB*rB*cos(betaAB_2*theta) - 3*bB*betaAB_1*rAB* &
        *3*cos(betaAB_2 *theta) + 2*bB*betaAB_1*rAB**2*rB*cos(betaAB_2*theta) + bB*rA*rAB **2 &
        - bB*rA*rAB*rB - bB*rAB**3 + bB*rAB**2*rB)
end function H

end module cht_04
