# Auto-generated by generate_code.py

import math

# Global constants
L = 1.0
T = 1.0
nu = 1.0
rho = 1.0
u0 = 1.0
alpha = 2
pi = 3.141592653589793

# Function p
def p(x, y):

    res = (1/4)*rho*u0**2*(math.cos(4*alpha*pi*x/L) + math.cos(4*alpha*pi*y/L))*math.exp(-16*alpha**2 \
        *nu*pi**2*t/L**2)
    return res

# Function u
def u(x, y):

    res = [0.0]*2
    res[0] = u0*math.exp(-8*alpha**2*nu*pi**2*t/L**2)*math.sin(2*alpha*pi*x/L)*math.cos(2*alpha*pi*y/L)
    res[1] = -u0*math.exp(-8*alpha**2*nu*pi**2*t/L**2)*math.sin(2*alpha*pi*y/L)*math.cos(2*alpha*pi*x/L)
    return res

# Function f
def f(x, y):

    res = [0.0]*2
    res[0] = 0
    res[1] = 0
    return res

# Function g
def g(x, y):

    res = 0
    return res
