% Auto-generated by generate_code.py

% Global constants
global L = 1.0;
global T = 1.0;
global nu = 1.0;
global rho = 1.0;
global u0 = 1.0;
global alpha = 2.0;
global pi = 3.141592653589793;

% Function p
function res = p(x, y)
    res = rho.*u0.^2.*(cos(4*alpha.*pi.*x./L) + cos(4*alpha.*pi.*y./L)).*exp(-16*alpha.^2.*nu.*pi.^2. ...
        *t./L.^2)/4;
end

% Function u
function res = u(x, y)
    res = zeros(2,1);
    res(1) = u0.*exp(-8*alpha.^2.*nu.*pi.^2.*t./L.^2).*sin(2*alpha.*pi.*x./L).*cos(2*alpha.*pi.*y./L);
    res(2) = -u0.*exp(-8*alpha.^2.*nu.*pi.^2.*t./L.^2).*sin(2*alpha.*pi.*y./L).*cos(2*alpha.*pi.*x./L);
end

% Function f
function res = f(x, y)
    res = zeros(2,1);
    res(1) = 0;
    res(2) = 0;
end

% Function g
function res = g(x, y)
    res = 0;
end
