# Auto-generated by generate_code.py

import math

# Global constants
rO = 1.0
rI = 0.5
nu = 1.0
rho = 1.0
omegaO = 1.0
omegaI = -2.0
pi = 3.141592653589793

# Function p
def p(x, y):

    res = rho*((1/2)*r**2*(-omegaI*rI**2 + omegaO*rO**2)**2/(-rI**2 + rO**2)**2 + 2*rI**2*rO**2*( \
        -omegaI + omegaO)*(-omegaI*rI**2 + omegaO*rO**2)*math.log(r)/(-rI**2 + rO**2)**2 - 1/2 \
        *rI**4*rO**4*(-omegaI + omegaO)**2/(r**2*(-rI**2 + rO**2)**2) - (-cI + cO)/(pi*(-rI**2 \
        + rO**2)))
    return res

# Function u
def u(x, y):

    res = [0.0]*2
    res[0] = -(r*(-omegaI*rI**2 + omegaO*rO**2)/(-rI**2 + rO**2) + rI**2*rO**2*(-omegaI + omegaO)/(r*( \
        -rI**2 + rO**2)))*math.sin(theta)
    res[1] = (r*(-omegaI*rI**2 + omegaO*rO**2)/(-rI**2 + rO**2) + rI**2*rO**2*(-omegaI + omegaO)/(r*( \
        -rI**2 + rO**2)))*math.cos(theta)
    return res

# Function f
def f(x, y):

    res = [0.0]*2
    res[0] = 0
    res[1] = 0
    return res

# Function g
def g(x, y):

    res = 0
    return res
