% Auto-generated by generate_code.py

% Global constants
global rO = 1.0;
global rI = 0.5;
global nu = 1.0;
global rho = 1.0;
global omegaO = 1.0;
global omegaI = -2.0;
global pi = 3.141592653589793;

% Function p
function res = p(x, y)
    global rO;
    global rI;
    global nu;
    global rho;
    global omegaO;
    global omegaI;
    global pi;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res = rho.*(r.^2.*(-omegaI.*rI.^2 + omegaO.*rO.^2).^2./(2*(-rI.^2 + rO.^2).^2) + 2*rI.^2.*rO.^2.*( ...
        -omegaI + omegaO).*(-omegaI.*rI.^2 + omegaO.*rO.^2).*log(r)./(-rI.^2 + rO.^2).^2 ...
        - rI.^4.*rO.^4.*(-omegaI + omegaO).^2./(2*r.^2.*(-rI.^2 + rO.^2).^2) - (-cI + cO). ...
        /(pi.*(-rI.^2 + rO.^2)));
end

% Function u
function res = u(x, y)
    global rO;
    global rI;
    global nu;
    global rho;
    global omegaO;
    global omegaI;
    global pi;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res = zeros(2,1);
    res(1) = -(r.*(-omegaI.*rI.^2 + omegaO.*rO.^2)./(-rI.^2 + rO.^2) + rI.^2.*rO.^2.*(-omegaI ...
        + omegaO)./(r.*(-rI.^2 + rO.^2))).*sin(theta);
    res(2) = (r.*(-omegaI.*rI.^2 + omegaO.*rO.^2)./(-rI.^2 + rO.^2) + rI.^2.*rO.^2.*(-omegaI + omegaO). ...
        /(r.*(-rI.^2 + rO.^2))).*cos(theta);
end

% Function f
function res = f(x, y)
    global rO;
    global rI;
    global nu;
    global rho;
    global omegaO;
    global omegaI;
    global pi;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res = zeros(2,1);
    res(1) = 0;
    res(2) = 0;
end

% Function g
function res = g(x, y)
    global rO;
    global rI;
    global nu;
    global rho;
    global omegaO;
    global omegaI;
    global pi;
    r = sqrt(x.^2 + y.^2);
    theta = atan2(y, x);
    res = 0;
end
